//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity TIMING in the absolutely scheduled peculiarity.
 * 
 * <p>Java class for ABSOLUTELY-SCHEDULED-TIMING-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ABSOLUTELY-SCHEDULED-TIMING-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml}DESC" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SLOT-ID" type="{http://www.asam.net/xml/fbx}SLOT-ID-TYPE"/>
 *         &lt;choice>
 *           &lt;element name="CYCLE-COUNTER" type="{http://www.asam.net/xml/fbx}CYCLE-COUNTER-TYPE"/>
 *           &lt;sequence>
 *             &lt;element name="BASE-CYCLE" type="{http://www.asam.net/xml/fbx}CYCLE-COUNTER-TYPE"/>
 *             &lt;element name="CYCLE-REPETITION" type="{http://www.asam.net/xml/fbx}CYCLE-REPETITION-TYPE"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-ABSOLUTELY-SCHEDULED-TIMING-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ABSOLUTELY-SCHEDULED-TIMING-TYPE", propOrder = {
    "desc",
    "slotid",
    "cyclecounter",
    "basecycle",
    "cyclerepetition",
    "manufacturerextension"
})
public class ABSOLUTELYSCHEDULEDTIMINGTYPE {

    @XmlElement(name = "DESC", namespace = "http://www.asam.net/xml")
    protected List<DESC> desc;
    @XmlElement(name = "SLOT-ID", required = true)
    protected BigInteger slotid;
    @XmlElement(name = "CYCLE-COUNTER")
    protected Short cyclecounter;
    @XmlElement(name = "BASE-CYCLE")
    protected Short basecycle;
    @XmlElement(name = "CYCLE-REPETITION")
    protected Short cyclerepetition;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERABSOLUTELYSCHEDULEDTIMINGEXTENSION manufacturerextension;

    /**
     * Gets the value of the desc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the desc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDESC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESC }
     * 
     * 
     */
    public List<DESC> getDESC() {
        if (desc == null) {
            desc = new ArrayList<DESC>();
        }
        return this.desc;
    }

    /**
     * Gets the value of the slotid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSLOTID() {
        return slotid;
    }

    /**
     * Sets the value of the slotid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSLOTID(BigInteger value) {
        this.slotid = value;
    }

    /**
     * Gets the value of the cyclecounter property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCYCLECOUNTER() {
        return cyclecounter;
    }

    /**
     * Sets the value of the cyclecounter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCYCLECOUNTER(Short value) {
        this.cyclecounter = value;
    }

    /**
     * Gets the value of the basecycle property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getBASECYCLE() {
        return basecycle;
    }

    /**
     * Sets the value of the basecycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setBASECYCLE(Short value) {
        this.basecycle = value;
    }

    /**
     * Gets the value of the cyclerepetition property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getCYCLEREPETITION() {
        return cyclerepetition;
    }

    /**
     * Sets the value of the cyclerepetition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setCYCLEREPETITION(Short value) {
        this.cyclerepetition = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERABSOLUTELYSCHEDULEDTIMINGEXTENSION }
     *     
     */
    public MANUFACTURERABSOLUTELYSCHEDULEDTIMINGEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERABSOLUTELYSCHEDULEDTIMINGEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERABSOLUTELYSCHEDULEDTIMINGEXTENSION value) {
        this.manufacturerextension = value;
    }

}
