//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACTIVE-CONDITION-SYSTEM-STATE-TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ACTIVE-CONDITION-SYSTEM-STATE-TYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CHANNEL_ACTIVE"/>
 *     &lt;enumeration value="CLAMP_15"/>
 *     &lt;enumeration value="CLAMP_30"/>
 *     &lt;enumeration value="CLAMP_87"/>
 *     &lt;enumeration value="CLAMP_RADIO"/>
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ACTIVE-CONDITION-SYSTEM-STATE-TYPE")
@XmlEnum
public enum ACTIVECONDITIONSYSTEMSTATETYPE {

    CHANNEL_ACTIVE,
    CLAMP_15,
    CLAMP_30,
    CLAMP_87,
    CLAMP_RADIO,
    NONE,
    OTHER;

    public String value() {
        return name();
    }

    public static ACTIVECONDITIONSYSTEMSTATETYPE fromValue(String v) {
        return valueOf(v);
    }

}
