//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * For reusability active conditions content model is specified using a type definition.
 * 
 * <p>Java class for ACTIVE-CONDITION-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACTIVE-CONDITION-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SYSTEM-TRIGGER" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="SYSTEM-STATE" type="{http://www.asam.net/xml/fbx}ACTIVE-CONDITION-SYSTEM-STATE-TYPE"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACTIVE-CONDITION-TYPE", propOrder = {
    "systemtrigger"
})
public class ACTIVECONDITIONTYPE {

    @XmlElement(name = "SYSTEM-TRIGGER", required = true)
    protected List<ACTIVECONDITIONTYPE.SYSTEMTRIGGER> systemtrigger;

    /**
     * Gets the value of the systemtrigger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemtrigger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSYSTEMTRIGGER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ACTIVECONDITIONTYPE.SYSTEMTRIGGER }
     * 
     * 
     */
    public List<ACTIVECONDITIONTYPE.SYSTEMTRIGGER> getSYSTEMTRIGGER() {
        if (systemtrigger == null) {
            systemtrigger = new ArrayList<ACTIVECONDITIONTYPE.SYSTEMTRIGGER>();
        }
        return this.systemtrigger;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="SYSTEM-STATE" type="{http://www.asam.net/xml/fbx}ACTIVE-CONDITION-SYSTEM-STATE-TYPE"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "systemstate"
    })
    public static class SYSTEMTRIGGER {

        @XmlElement(name = "SYSTEM-STATE", required = true)
        protected List<ACTIVECONDITIONSYSTEMSTATETYPE> systemstate;

        /**
         * Gets the value of the systemstate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the systemstate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSYSTEMSTATE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ACTIVECONDITIONSYSTEMSTATETYPE }
         * 
         * 
         */
        public List<ACTIVECONDITIONSYSTEMSTATETYPE> getSYSTEMSTATE() {
            if (systemstate == null) {
                systemstate = new ArrayList<ACTIVECONDITIONSYSTEMSTATETYPE>();
            }
            return this.systemstate;
        }

    }

}
