//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DOC-REVISIONS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DOC-REVISION" type="{http://www.asam.net/xml}REVISION-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "docrevisions"
})
@XmlRootElement(name = "ADMIN-DATA", namespace = "http://www.asam.net/xml")
public class ADMINDATA {

    @XmlElement(name = "DOC-REVISIONS", namespace = "http://www.asam.net/xml")
    protected ADMINDATA.DOCREVISIONS docrevisions;

    /**
     * Gets the value of the docrevisions property.
     * 
     * @return
     *     possible object is
     *     {@link ADMINDATA.DOCREVISIONS }
     *     
     */
    public ADMINDATA.DOCREVISIONS getDOCREVISIONS() {
        return docrevisions;
    }

    /**
     * Sets the value of the docrevisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADMINDATA.DOCREVISIONS }
     *     
     */
    public void setDOCREVISIONS(ADMINDATA.DOCREVISIONS value) {
        this.docrevisions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DOC-REVISION" type="{http://www.asam.net/xml}REVISION-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "docrevision"
    })
    public static class DOCREVISIONS {

        @XmlElement(name = "DOC-REVISION", namespace = "http://www.asam.net/xml", required = true)
        protected List<REVISIONTYPE> docrevision;

        /**
         * Gets the value of the docrevision property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the docrevision property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDOCREVISION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link REVISIONTYPE }
         * 
         * 
         */
        public List<REVISIONTYPE> getDOCREVISION() {
            if (docrevision == null) {
                docrevision = new ArrayList<REVISIONTYPE>();
            }
            return this.docrevision;
        }

    }

}
