//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CATEGORY.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CATEGORY">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="LEADING-LENGTH-INFO-TYPE"/>
 *     &lt;enumeration value="END-OF-PDU"/>
 *     &lt;enumeration value="MIN-MAX-LENGTH-TYPE"/>
 *     &lt;enumeration value="STANDARD-LENGTH-TYPE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CATEGORY", namespace = "http://www.asam.net/xml")
@XmlEnum
public enum CATEGORY {

    @XmlEnumValue("LEADING-LENGTH-INFO-TYPE")
    LEADING_LENGTH_INFO_TYPE("LEADING-LENGTH-INFO-TYPE"),
    @XmlEnumValue("END-OF-PDU")
    END_OF_PDU("END-OF-PDU"),
    @XmlEnumValue("MIN-MAX-LENGTH-TYPE")
    MIN_MAX_LENGTH_TYPE("MIN-MAX-LENGTH-TYPE"),
    @XmlEnumValue("STANDARD-LENGTH-TYPE")
    STANDARD_LENGTH_TYPE("STANDARD-LENGTH-TYPE");
    private final String value;

    CATEGORY(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CATEGORY fromValue(String v) {
        for (CATEGORY c: CATEGORY.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
