//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity CHANNEL with platform specific extendability.
 * 
 * <p>Java class for CHANNEL-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CHANNEL-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="PDU-TRIGGERINGS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PDU-TRIGGERING" type="{http://www.asam.net/xml/fbx}PDU-TRIGGERING-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FRAME-TRIGGERINGS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FRAME-TRIGGERING" type="{http://www.asam.net/xml/fbx}FRAME-TRIGGERING-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-CHANNEL-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CHANNEL-TYPE", propOrder = {
    "pdutriggerings",
    "frametriggerings",
    "manufacturerextension"
})
public class CHANNELTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "PDU-TRIGGERINGS")
    protected CHANNELTYPE.PDUTRIGGERINGS pdutriggerings;
    @XmlElement(name = "FRAME-TRIGGERINGS")
    protected CHANNELTYPE.FRAMETRIGGERINGS frametriggerings;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERCHANNELEXTENSION manufacturerextension;

    /**
     * Gets the value of the pdutriggerings property.
     * 
     * @return
     *     possible object is
     *     {@link CHANNELTYPE.PDUTRIGGERINGS }
     *     
     */
    public CHANNELTYPE.PDUTRIGGERINGS getPDUTRIGGERINGS() {
        return pdutriggerings;
    }

    /**
     * Sets the value of the pdutriggerings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHANNELTYPE.PDUTRIGGERINGS }
     *     
     */
    public void setPDUTRIGGERINGS(CHANNELTYPE.PDUTRIGGERINGS value) {
        this.pdutriggerings = value;
    }

    /**
     * Gets the value of the frametriggerings property.
     * 
     * @return
     *     possible object is
     *     {@link CHANNELTYPE.FRAMETRIGGERINGS }
     *     
     */
    public CHANNELTYPE.FRAMETRIGGERINGS getFRAMETRIGGERINGS() {
        return frametriggerings;
    }

    /**
     * Sets the value of the frametriggerings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHANNELTYPE.FRAMETRIGGERINGS }
     *     
     */
    public void setFRAMETRIGGERINGS(CHANNELTYPE.FRAMETRIGGERINGS value) {
        this.frametriggerings = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERCHANNELEXTENSION }
     *     
     */
    public MANUFACTURERCHANNELEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERCHANNELEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERCHANNELEXTENSION value) {
        this.manufacturerextension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FRAME-TRIGGERING" type="{http://www.asam.net/xml/fbx}FRAME-TRIGGERING-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "frametriggering"
    })
    public static class FRAMETRIGGERINGS {

        @XmlElement(name = "FRAME-TRIGGERING", required = true)
        protected List<FRAMETRIGGERINGTYPE> frametriggering;

        /**
         * Gets the value of the frametriggering property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the frametriggering property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFRAMETRIGGERING().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FRAMETRIGGERINGTYPE }
         * 
         * 
         */
        public List<FRAMETRIGGERINGTYPE> getFRAMETRIGGERING() {
            if (frametriggering == null) {
                frametriggering = new ArrayList<FRAMETRIGGERINGTYPE>();
            }
            return this.frametriggering;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PDU-TRIGGERING" type="{http://www.asam.net/xml/fbx}PDU-TRIGGERING-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pdutriggering"
    })
    public static class PDUTRIGGERINGS {

        @XmlElement(name = "PDU-TRIGGERING", required = true)
        protected List<PDUTRIGGERINGTYPE> pdutriggering;

        /**
         * Gets the value of the pdutriggering property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pdutriggering property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPDUTRIGGERING().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PDUTRIGGERINGTYPE }
         * 
         * 
         */
        public List<PDUTRIGGERINGTYPE> getPDUTRIGGERING() {
            if (pdutriggering == null) {
                pdutriggering = new ArrayList<PDUTRIGGERINGTYPE>();
            }
            return this.pdutriggering;
        }

    }

}
