//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.asam.net/xml}BIT-LENGTH"/>
 *         &lt;sequence>
 *           &lt;element name="MIN-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *           &lt;element name="MAX-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *       &lt;attribute ref="{http://www.asam.net/xml}BASE-DATA-TYPE"/>
 *       &lt;attribute name="CATEGORY" use="required" type="{http://www.asam.net/xml}CATEGORY" />
 *       &lt;attribute name="ENCODING" type="{http://www.asam.net/xml}ENCODING" />
 *       &lt;attribute name="TERMINATION" type="{http://www.asam.net/xml}TERMINATION" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bitlength",
    "minlength",
    "maxlength"
})
@XmlRootElement(name = "CODED-TYPE", namespace = "http://www.asam.net/xml")
public class CODEDTYPE {

    @XmlElement(name = "BIT-LENGTH", namespace = "http://www.asam.net/xml")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bitlength;
    @XmlElement(name = "MIN-LENGTH", namespace = "http://www.asam.net/xml")
    @XmlSchemaType(name = "unsignedInt")
    protected Long minlength;
    @XmlElement(name = "MAX-LENGTH", namespace = "http://www.asam.net/xml")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxlength;
    @XmlAttribute(name = "BASE-DATA-TYPE", namespace = "http://www.asam.net/xml")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String basedatatype;
    @XmlAttribute(name = "CATEGORY", required = true)
    protected CATEGORY category;
    @XmlAttribute(name = "ENCODING")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String encoding;
    @XmlAttribute(name = "TERMINATION")
    protected TERMINATION termination;

    /**
     * Gets the value of the bitlength property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBITLENGTH() {
        return bitlength;
    }

    /**
     * Sets the value of the bitlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBITLENGTH(Long value) {
        this.bitlength = value;
    }

    /**
     * Gets the value of the minlength property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMINLENGTH() {
        return minlength;
    }

    /**
     * Sets the value of the minlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMINLENGTH(Long value) {
        this.minlength = value;
    }

    /**
     * Gets the value of the maxlength property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMAXLENGTH() {
        return maxlength;
    }

    /**
     * Sets the value of the maxlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMAXLENGTH(Long value) {
        this.maxlength = value;
    }

    /**
     * Gets the value of the basedatatype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBASEDATATYPE() {
        return basedatatype;
    }

    /**
     * Sets the value of the basedatatype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBASEDATATYPE(String value) {
        this.basedatatype = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link CATEGORY }
     *     
     */
    public CATEGORY getCATEGORY() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link CATEGORY }
     *     
     */
    public void setCATEGORY(CATEGORY value) {
        this.category = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENCODING() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENCODING(String value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the termination property.
     * 
     * @return
     *     possible object is
     *     {@link TERMINATION }
     *     
     */
    public TERMINATION getTERMINATION() {
        return termination;
    }

    /**
     * Sets the value of the termination property.
     * 
     * @param value
     *     allowed object is
     *     {@link TERMINATION }
     *     
     */
    public void setTERMINATION(TERMINATION value) {
        this.termination = value;
    }

}
