//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for COMPU-CATEGORY.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="COMPU-CATEGORY">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="IDENTICAL"/>
 *     &lt;enumeration value="LINEAR"/>
 *     &lt;enumeration value="SCALE-LINEAR"/>
 *     &lt;enumeration value="TEXTTABLE"/>
 *     &lt;enumeration value="TAB-NOINTP"/>
 *     &lt;enumeration value="FORMULA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "COMPU-CATEGORY", namespace = "http://www.asam.net/xml")
@XmlEnum
public enum COMPUCATEGORY {

    IDENTICAL("IDENTICAL"),
    LINEAR("LINEAR"),
    @XmlEnumValue("SCALE-LINEAR")
    SCALE_LINEAR("SCALE-LINEAR"),
    TEXTTABLE("TEXTTABLE"),
    @XmlEnumValue("TAB-NOINTP")
    TAB_NOINTP("TAB-NOINTP"),
    FORMULA("FORMULA");
    private final String value;

    COMPUCATEGORY(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static COMPUCATEGORY fromValue(String v) {
        for (COMPUCATEGORY c: COMPUCATEGORY.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
