//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity COMPOSITE
 * 
 * <p>Java class for COMPOSITE-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COMPOSITE-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="COMPOSITION-LEVEL" type="{http://www.asam.net/xml/fbx}COMPOSITION-LEVEL-TYPE" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="COMPOSITE-REFS">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.asam.net/xml/fbx}COMPOSITE-REF" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="PDU-REFS">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.asam.net/xml/fbx}PDU-REF" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ECU-REFS">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.asam.net/xml/fbx}ECU-REF" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="FUNCTION-REFS">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://www.asam.net/xml/fbx}FUNCTION-REF" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SIGNAL-REFS">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="SIGNAL-REF" type="{http://www.asam.net/xml/fbx}SIGNAL-REF" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-COMPOSITE-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPOSITE-TYPE", propOrder = {
    "compositionlevel",
    "compositerefs",
    "pdurefs",
    "ecurefs",
    "functionrefs",
    "signalrefs",
    "manufacturerextension"
})
public class COMPOSITETYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "COMPOSITION-LEVEL")
    protected String compositionlevel;
    @XmlElement(name = "COMPOSITE-REFS")
    protected COMPOSITETYPE.COMPOSITEREFS compositerefs;
    @XmlElement(name = "PDU-REFS")
    protected COMPOSITETYPE.PDUREFS pdurefs;
    @XmlElement(name = "ECU-REFS")
    protected COMPOSITETYPE.ECUREFS ecurefs;
    @XmlElement(name = "FUNCTION-REFS")
    protected COMPOSITETYPE.FUNCTIONREFS functionrefs;
    @XmlElement(name = "SIGNAL-REFS")
    protected COMPOSITETYPE.SIGNALREFS signalrefs;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERCOMPOSITEEXTENSION manufacturerextension;

    /**
     * Gets the value of the compositionlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPOSITIONLEVEL() {
        return compositionlevel;
    }

    /**
     * Sets the value of the compositionlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPOSITIONLEVEL(String value) {
        this.compositionlevel = value;
    }

    /**
     * Gets the value of the compositerefs property.
     * 
     * @return
     *     possible object is
     *     {@link COMPOSITETYPE.COMPOSITEREFS }
     *     
     */
    public COMPOSITETYPE.COMPOSITEREFS getCOMPOSITEREFS() {
        return compositerefs;
    }

    /**
     * Sets the value of the compositerefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPOSITETYPE.COMPOSITEREFS }
     *     
     */
    public void setCOMPOSITEREFS(COMPOSITETYPE.COMPOSITEREFS value) {
        this.compositerefs = value;
    }

    /**
     * Gets the value of the pdurefs property.
     * 
     * @return
     *     possible object is
     *     {@link COMPOSITETYPE.PDUREFS }
     *     
     */
    public COMPOSITETYPE.PDUREFS getPDUREFS() {
        return pdurefs;
    }

    /**
     * Sets the value of the pdurefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPOSITETYPE.PDUREFS }
     *     
     */
    public void setPDUREFS(COMPOSITETYPE.PDUREFS value) {
        this.pdurefs = value;
    }

    /**
     * Gets the value of the ecurefs property.
     * 
     * @return
     *     possible object is
     *     {@link COMPOSITETYPE.ECUREFS }
     *     
     */
    public COMPOSITETYPE.ECUREFS getECUREFS() {
        return ecurefs;
    }

    /**
     * Sets the value of the ecurefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPOSITETYPE.ECUREFS }
     *     
     */
    public void setECUREFS(COMPOSITETYPE.ECUREFS value) {
        this.ecurefs = value;
    }

    /**
     * Gets the value of the functionrefs property.
     * 
     * @return
     *     possible object is
     *     {@link COMPOSITETYPE.FUNCTIONREFS }
     *     
     */
    public COMPOSITETYPE.FUNCTIONREFS getFUNCTIONREFS() {
        return functionrefs;
    }

    /**
     * Sets the value of the functionrefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPOSITETYPE.FUNCTIONREFS }
     *     
     */
    public void setFUNCTIONREFS(COMPOSITETYPE.FUNCTIONREFS value) {
        this.functionrefs = value;
    }

    /**
     * Gets the value of the signalrefs property.
     * 
     * @return
     *     possible object is
     *     {@link COMPOSITETYPE.SIGNALREFS }
     *     
     */
    public COMPOSITETYPE.SIGNALREFS getSIGNALREFS() {
        return signalrefs;
    }

    /**
     * Sets the value of the signalrefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPOSITETYPE.SIGNALREFS }
     *     
     */
    public void setSIGNALREFS(COMPOSITETYPE.SIGNALREFS value) {
        this.signalrefs = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERCOMPOSITEEXTENSION }
     *     
     */
    public MANUFACTURERCOMPOSITEEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERCOMPOSITEEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERCOMPOSITEEXTENSION value) {
        this.manufacturerextension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}COMPOSITE-REF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "compositeref"
    })
    public static class COMPOSITEREFS {

        @XmlElement(name = "COMPOSITE-REF", required = true)
        protected List<COMPOSITEREF> compositeref;

        /**
         * Gets the value of the compositeref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the compositeref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCOMPOSITEREF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link COMPOSITEREF }
         * 
         * 
         */
        public List<COMPOSITEREF> getCOMPOSITEREF() {
            if (compositeref == null) {
                compositeref = new ArrayList<COMPOSITEREF>();
            }
            return this.compositeref;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}ECU-REF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ecuref"
    })
    public static class ECUREFS {

        @XmlElement(name = "ECU-REF", required = true)
        protected List<ECUREF> ecuref;

        /**
         * Refering a subordenated composite.Gets the value of the ecuref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ecuref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getECUREF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ECUREF }
         * 
         * 
         */
        public List<ECUREF> getECUREF() {
            if (ecuref == null) {
                ecuref = new ArrayList<ECUREF>();
            }
            return this.ecuref;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}FUNCTION-REF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "functionref"
    })
    public static class FUNCTIONREFS {

        @XmlElement(name = "FUNCTION-REF", required = true)
        protected List<FUNCTIONREF> functionref;

        /**
         * Refering a subordenated composite.Gets the value of the functionref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the functionref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFUNCTIONREF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FUNCTIONREF }
         * 
         * 
         */
        public List<FUNCTIONREF> getFUNCTIONREF() {
            if (functionref == null) {
                functionref = new ArrayList<FUNCTIONREF>();
            }
            return this.functionref;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}PDU-REF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pduref"
    })
    public static class PDUREFS {

        @XmlElement(name = "PDU-REF", required = true)
        protected List<PDUREF> pduref;

        /**
         * Refering a subordenated composite.Gets the value of the pduref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pduref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPDUREF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PDUREF }
         * 
         * 
         */
        public List<PDUREF> getPDUREF() {
            if (pduref == null) {
                pduref = new ArrayList<PDUREF>();
            }
            return this.pduref;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SIGNAL-REF" type="{http://www.asam.net/xml/fbx}SIGNAL-REF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signalref"
    })
    public static class SIGNALREFS {

        @XmlElement(name = "SIGNAL-REF", required = true)
        protected List<SIGNALREF> signalref;

        /**
         * Gets the value of the signalref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the signalref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSIGNALREF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SIGNALREF }
         * 
         * 
         */
        public List<SIGNALREF> getSIGNALREF() {
            if (signalref == null) {
                signalref = new ArrayList<SIGNALREF>();
            }
            return this.signalref;
        }

    }

}
