//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Describing a company involved in project
 * 
 * <p>Java class for COMPANY-DATA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COMPANY-DATA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.asam.net/xml}NAME-DETAILS"/>
 *         &lt;element name="TEAM-MEMBERS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TEAM-MEMBER" type="{http://www.asam.net/xml}TEAM-MEMBER" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="ROLE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="MANUFACTURER"/>
 *             &lt;enumeration value="SUPPLIER"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPANY-DATA", namespace = "http://www.asam.net/xml", propOrder = {
    "shortname",
    "longname",
    "desc",
    "teammembers"
})
public class COMPANYDATA {

    @XmlElement(name = "SHORT-NAME", required = true)
    protected String shortname;
    @XmlElement(name = "LONG-NAME")
    protected List<LONGNAME> longname;
    @XmlElement(name = "DESC")
    protected List<DESC> desc;
    @XmlElement(name = "TEAM-MEMBERS")
    protected COMPANYDATA.TEAMMEMBERS teammembers;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "ROLE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String role;

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHORTNAME() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHORTNAME(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the longname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the longname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLONGNAME().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LONGNAME }
     * 
     * 
     */
    public List<LONGNAME> getLONGNAME() {
        if (longname == null) {
            longname = new ArrayList<LONGNAME>();
        }
        return this.longname;
    }

    /**
     * Gets the value of the desc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the desc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDESC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESC }
     * 
     * 
     */
    public List<DESC> getDESC() {
        if (desc == null) {
            desc = new ArrayList<DESC>();
        }
        return this.desc;
    }

    /**
     * Gets the value of the teammembers property.
     * 
     * @return
     *     possible object is
     *     {@link COMPANYDATA.TEAMMEMBERS }
     *     
     */
    public COMPANYDATA.TEAMMEMBERS getTEAMMEMBERS() {
        return teammembers;
    }

    /**
     * Sets the value of the teammembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPANYDATA.TEAMMEMBERS }
     *     
     */
    public void setTEAMMEMBERS(COMPANYDATA.TEAMMEMBERS value) {
        this.teammembers = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROLE() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROLE(String value) {
        this.role = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TEAM-MEMBER" type="{http://www.asam.net/xml}TEAM-MEMBER" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "teammember"
    })
    public static class TEAMMEMBERS {

        @XmlElement(name = "TEAM-MEMBER", namespace = "http://www.asam.net/xml", required = true)
        protected List<TEAMMEMBER> teammember;

        /**
         * Gets the value of the teammember property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the teammember property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTEAMMEMBER().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TEAMMEMBER }
         * 
         * 
         */
        public List<TEAMMEMBER> getTEAMMEMBER() {
            if (teammember == null) {
                teammember = new ArrayList<TEAMMEMBER>();
            }
            return this.teammember;
        }

    }

}
