//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Domain and computition rule to convert an internal data (transmitted over the communication system) into phyiscal data of an application.
 * 
 * <p>Java class for COMPU-SCALE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="COMPU-SCALE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml}DESC" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LOWER-LIMIT" type="{http://www.asam.net/xml}INTERVAL-TYPE" minOccurs="0"/>
 *         &lt;element name="UPPER-LIMIT" type="{http://www.asam.net/xml}INTERVAL-TYPE" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="COMPU-CONST">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;choice>
 *                     &lt;element ref="{http://www.asam.net/xml}V"/>
 *                     &lt;element ref="{http://www.asam.net/xml}VT"/>
 *                   &lt;/choice>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="COMPU-RATIONAL-COEFFS" type="{http://www.asam.net/xml}COMPU-RATIONAL-COEFFS"/>
 *           &lt;element name="COMPU-GENERIC-MATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COMPU-SCALE", namespace = "http://www.asam.net/xml", propOrder = {
    "desc",
    "lowerlimit",
    "upperlimit",
    "compuconst",
    "compurationalcoeffs",
    "compugenericmath"
})
public class COMPUSCALE {

    @XmlElement(name = "DESC")
    protected List<DESC> desc;
    @XmlElement(name = "LOWER-LIMIT")
    protected INTERVALTYPE lowerlimit;
    @XmlElement(name = "UPPER-LIMIT")
    protected INTERVALTYPE upperlimit;
    @XmlElement(name = "COMPU-CONST")
    protected COMPUSCALE.COMPUCONST compuconst;
    @XmlElement(name = "COMPU-RATIONAL-COEFFS")
    protected COMPURATIONALCOEFFS compurationalcoeffs;
    @XmlElement(name = "COMPU-GENERIC-MATH")
    protected String compugenericmath;

    /**
     * Gets the value of the desc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the desc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDESC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESC }
     * 
     * 
     */
    public List<DESC> getDESC() {
        if (desc == null) {
            desc = new ArrayList<DESC>();
        }
        return this.desc;
    }

    /**
     * Gets the value of the lowerlimit property.
     * 
     * @return
     *     possible object is
     *     {@link INTERVALTYPE }
     *     
     */
    public INTERVALTYPE getLOWERLIMIT() {
        return lowerlimit;
    }

    /**
     * Sets the value of the lowerlimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link INTERVALTYPE }
     *     
     */
    public void setLOWERLIMIT(INTERVALTYPE value) {
        this.lowerlimit = value;
    }

    /**
     * Gets the value of the upperlimit property.
     * 
     * @return
     *     possible object is
     *     {@link INTERVALTYPE }
     *     
     */
    public INTERVALTYPE getUPPERLIMIT() {
        return upperlimit;
    }

    /**
     * Sets the value of the upperlimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link INTERVALTYPE }
     *     
     */
    public void setUPPERLIMIT(INTERVALTYPE value) {
        this.upperlimit = value;
    }

    /**
     * Gets the value of the compuconst property.
     * 
     * @return
     *     possible object is
     *     {@link COMPUSCALE.COMPUCONST }
     *     
     */
    public COMPUSCALE.COMPUCONST getCOMPUCONST() {
        return compuconst;
    }

    /**
     * Sets the value of the compuconst property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPUSCALE.COMPUCONST }
     *     
     */
    public void setCOMPUCONST(COMPUSCALE.COMPUCONST value) {
        this.compuconst = value;
    }

    /**
     * Gets the value of the compurationalcoeffs property.
     * 
     * @return
     *     possible object is
     *     {@link COMPURATIONALCOEFFS }
     *     
     */
    public COMPURATIONALCOEFFS getCOMPURATIONALCOEFFS() {
        return compurationalcoeffs;
    }

    /**
     * Sets the value of the compurationalcoeffs property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPURATIONALCOEFFS }
     *     
     */
    public void setCOMPURATIONALCOEFFS(COMPURATIONALCOEFFS value) {
        this.compurationalcoeffs = value;
    }

    /**
     * Gets the value of the compugenericmath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPUGENERICMATH() {
        return compugenericmath;
    }

    /**
     * Sets the value of the compugenericmath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPUGENERICMATH(String value) {
        this.compugenericmath = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.asam.net/xml}V"/>
     *         &lt;element ref="{http://www.asam.net/xml}VT"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "v",
        "vt"
    })
    public static class COMPUCONST {

        @XmlElement(name = "V", namespace = "http://www.asam.net/xml")
        protected Double v;
        @XmlElement(name = "VT", namespace = "http://www.asam.net/xml")
        protected String vt;

        /**
         * Gets the value of the v property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getV() {
            return v;
        }

        /**
         * Sets the value of the v property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setV(Double value) {
            this.v = value;
        }

        /**
         * Gets the value of the vt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVT() {
            return vt;
        }

        /**
         * Sets the value of the vt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVT(String value) {
            this.vt = value;
        }

    }

}
