//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * ECU relevant diagnostic addresses
 * 
 * <p>Java class for DIAGNOSTIC-ADDRESSES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DIAGNOSTIC-ADDRESSES">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RESPONSE-ADDRESS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TP-ADDRESS-REF" type="{http://www.asam.net/xml/fbx}TP-ADDRESS-REF-BASETYPE"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TP-ADDRESS-REFS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.asam.net/xml/fbx}TP-ADDRESS-REF" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DIAGNOSTIC-ADDRESSES", propOrder = {
    "responseaddress",
    "tpaddressrefs"
})
public class DIAGNOSTICADDRESSES {

    @XmlElement(name = "RESPONSE-ADDRESS")
    protected DIAGNOSTICADDRESSES.RESPONSEADDRESS responseaddress;
    @XmlElement(name = "TP-ADDRESS-REFS")
    protected DIAGNOSTICADDRESSES.TPADDRESSREFS tpaddressrefs;

    /**
     * Gets the value of the responseaddress property.
     * 
     * @return
     *     possible object is
     *     {@link DIAGNOSTICADDRESSES.RESPONSEADDRESS }
     *     
     */
    public DIAGNOSTICADDRESSES.RESPONSEADDRESS getRESPONSEADDRESS() {
        return responseaddress;
    }

    /**
     * Sets the value of the responseaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DIAGNOSTICADDRESSES.RESPONSEADDRESS }
     *     
     */
    public void setRESPONSEADDRESS(DIAGNOSTICADDRESSES.RESPONSEADDRESS value) {
        this.responseaddress = value;
    }

    /**
     * Gets the value of the tpaddressrefs property.
     * 
     * @return
     *     possible object is
     *     {@link DIAGNOSTICADDRESSES.TPADDRESSREFS }
     *     
     */
    public DIAGNOSTICADDRESSES.TPADDRESSREFS getTPADDRESSREFS() {
        return tpaddressrefs;
    }

    /**
     * Sets the value of the tpaddressrefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link DIAGNOSTICADDRESSES.TPADDRESSREFS }
     *     
     */
    public void setTPADDRESSREFS(DIAGNOSTICADDRESSES.TPADDRESSREFS value) {
        this.tpaddressrefs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TP-ADDRESS-REF" type="{http://www.asam.net/xml/fbx}TP-ADDRESS-REF-BASETYPE"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tpaddressref"
    })
    public static class RESPONSEADDRESS {

        @XmlElement(name = "TP-ADDRESS-REF", required = true)
        protected TPADDRESSREFBASETYPE tpaddressref;

        /**
         * Gets the value of the tpaddressref property.
         * 
         * @return
         *     possible object is
         *     {@link TPADDRESSREFBASETYPE }
         *     
         */
        public TPADDRESSREFBASETYPE getTPADDRESSREF() {
            return tpaddressref;
        }

        /**
         * Sets the value of the tpaddressref property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPADDRESSREFBASETYPE }
         *     
         */
        public void setTPADDRESSREF(TPADDRESSREFBASETYPE value) {
            this.tpaddressref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}TP-ADDRESS-REF" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tpaddressref"
    })
    public static class TPADDRESSREFS {

        @XmlElement(name = "TP-ADDRESS-REF", required = true)
        protected List<TPADDRESSREF> tpaddressref;

        /**
         * Gets the value of the tpaddressref property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tpaddressref property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTPADDRESSREF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPADDRESSREF }
         * 
         * 
         */
        public List<TPADDRESSREF> getTPADDRESSREF() {
            if (tpaddressref == null) {
                tpaddressref = new ArrayList<TPADDRESSREF>();
            }
            return this.tpaddressref;
        }

    }

}
