//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Describes, which value of the SIGNAL is to be send dependent on the current system state. The value corresponds to the CONSTRS in COMPU-METHOD
 * 
 * <p>Java class for ECU-SENDING-BEHAVIOR-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECU-SENDING-BEHAVIOR-TYPE">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.asam.net/xml/fbx>ECU-SENDING-BEHAVIOR-BASETYPE">
 *       &lt;attribute name="SYSTEM-STATE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="CLAMP_15_ON"/>
 *             &lt;enumeration value="CLAMP_15_OFF"/>
 *             &lt;enumeration value="CLAMP_30_ON"/>
 *             &lt;enumeration value="CLAMP_30_OFF"/>
 *             &lt;enumeration value="CLAMP_87_ON"/>
 *             &lt;enumeration value="CLAMP_87_OFF"/>
 *             &lt;enumeration value="CLAMP_RADIO_ON"/>
 *             &lt;enumeration value="CLAMP_RADIO_OFF"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECU-SENDING-BEHAVIOR-TYPE", propOrder = {
    "value"
})
public class ECUSENDINGBEHAVIORTYPE {

    @XmlValue
    protected ECUSENDINGBEHAVIORBASETYPE value;
    @XmlAttribute(name = "SYSTEM-STATE")
    protected String systemstate;

    /**
     * Base type for ECU-SENDING-BEHAVIOR-TYPE (XML schema does not allow a restriction with enumerations together with extension for an attribute)
     * 
     * @return
     *     possible object is
     *     {@link ECUSENDINGBEHAVIORBASETYPE }
     *     
     */
    public ECUSENDINGBEHAVIORBASETYPE getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECUSENDINGBEHAVIORBASETYPE }
     *     
     */
    public void setValue(ECUSENDINGBEHAVIORBASETYPE value) {
        this.value = value;
    }

    /**
     * Gets the value of the systemstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYSTEMSTATE() {
        return systemstate;
    }

    /**
     * Sets the value of the systemstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYSTEMSTATE(String value) {
        this.systemstate = value;
    }

}
