//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EXECUTE-CONDITION-SYSTEM-STATE-TYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EXECUTE-CONDITION-SYSTEM-STATE-TYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CHANNEL_ACTIVE_ON"/>
 *     &lt;enumeration value="CHANNEL_ACTIVE_OFF"/>
 *     &lt;enumeration value="CLAMP_15_ON"/>
 *     &lt;enumeration value="CLAMP_15_OFF"/>
 *     &lt;enumeration value="CLAMP_30_ON"/>
 *     &lt;enumeration value="CLAMP_30_OFF"/>
 *     &lt;enumeration value="CLAMP_87_ON"/>
 *     &lt;enumeration value="CLAMP_87_OFF"/>
 *     &lt;enumeration value="CLAMP_RADIO_ON"/>
 *     &lt;enumeration value="CLAMP_RADIO_OFF"/>
 *     &lt;enumeration value="KEY_PRESSED"/>
 *     &lt;enumeration value="KEY_RELEASED"/>
 *     &lt;enumeration value="NO_OTHER_TRIGGERING_RUNNING"/>
 *     &lt;enumeration value="OTHER_TRIGGERING_RUNNING"/>
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EXECUTE-CONDITION-SYSTEM-STATE-TYPE")
@XmlEnum
public enum EXECUTECONDITIONSYSTEMSTATETYPE {

    CHANNEL_ACTIVE_ON,
    CHANNEL_ACTIVE_OFF,
    CLAMP_15_ON,
    CLAMP_15_OFF,
    CLAMP_30_ON,
    CLAMP_30_OFF,
    CLAMP_87_ON,
    CLAMP_87_OFF,
    CLAMP_RADIO_ON,
    CLAMP_RADIO_OFF,
    KEY_PRESSED,
    KEY_RELEASED,
    NO_OTHER_TRIGGERING_RUNNING,
    OTHER_TRIGGERING_RUNNING,
    NONE,
    OTHER;

    public String value() {
        return name();
    }

    public static EXECUTECONDITIONSYSTEMSTATETYPE fromValue(String v) {
        return valueOf(v);
    }

}
