//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * For reusability execute conditions content model is specified using a type definition.
 * 
 * <p>Java class for EXECUTE-CONDITION-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EXECUTE-CONDITION-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SYSTEM-TRIGGER" type="{http://www.asam.net/xml/fbx}SYSTEM-TRIGGER" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SIGNAL-TRIGGER" type="{http://www.asam.net/xml/fbx}SIGNAL-TRIGGER" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EXECUTE-CONDITION-TYPE", propOrder = {
    "systemtrigger",
    "signaltrigger"
})
public class EXECUTECONDITIONTYPE {

    @XmlElement(name = "SYSTEM-TRIGGER")
    protected List<SYSTEMTRIGGER> systemtrigger;
    @XmlElement(name = "SIGNAL-TRIGGER")
    protected List<SIGNALTRIGGER> signaltrigger;

    /**
     * Gets the value of the systemtrigger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemtrigger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSYSTEMTRIGGER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SYSTEMTRIGGER }
     * 
     * 
     */
    public List<SYSTEMTRIGGER> getSYSTEMTRIGGER() {
        if (systemtrigger == null) {
            systemtrigger = new ArrayList<SYSTEMTRIGGER>();
        }
        return this.systemtrigger;
    }

    /**
     * Gets the value of the signaltrigger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signaltrigger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSIGNALTRIGGER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SIGNALTRIGGER }
     * 
     * 
     */
    public List<SIGNALTRIGGER> getSIGNALTRIGGER() {
        if (signaltrigger == null) {
            signaltrigger = new ArrayList<SIGNALTRIGGER>();
        }
        return this.signaltrigger;
    }

}
