//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Additional data of a company involved in FIBEX project.
 * 
 * <p>Java class for FIBEX-COMPANY-DATA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FIBEX-COMPANY-DATA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml}COMPANY-DATA-REF"/>
 *         &lt;element name="LIN-COMPANY-ID" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="PRODUCTS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PRODUCT" type="{http://www.asam.net/xml/fbx}PRODUCT-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FIBEX-COMPANY-DATA", propOrder = {
    "companydataref",
    "lincompanyid",
    "products"
})
public class FIBEXCOMPANYDATA {

    @XmlElement(name = "COMPANY-DATA-REF", namespace = "http://www.asam.net/xml", required = true)
    protected COMPANYDATAREF companydataref;
    @XmlElement(name = "LIN-COMPANY-ID")
    protected BigInteger lincompanyid;
    @XmlElement(name = "PRODUCTS")
    protected FIBEXCOMPANYDATA.PRODUCTS products;

    /**
     * Gets the value of the companydataref property.
     * 
     * @return
     *     possible object is
     *     {@link COMPANYDATAREF }
     *     
     */
    public COMPANYDATAREF getCOMPANYDATAREF() {
        return companydataref;
    }

    /**
     * Sets the value of the companydataref property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPANYDATAREF }
     *     
     */
    public void setCOMPANYDATAREF(COMPANYDATAREF value) {
        this.companydataref = value;
    }

    /**
     * Gets the value of the lincompanyid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLINCOMPANYID() {
        return lincompanyid;
    }

    /**
     * Sets the value of the lincompanyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLINCOMPANYID(BigInteger value) {
        this.lincompanyid = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link FIBEXCOMPANYDATA.PRODUCTS }
     *     
     */
    public FIBEXCOMPANYDATA.PRODUCTS getPRODUCTS() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link FIBEXCOMPANYDATA.PRODUCTS }
     *     
     */
    public void setPRODUCTS(FIBEXCOMPANYDATA.PRODUCTS value) {
        this.products = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PRODUCT" type="{http://www.asam.net/xml/fbx}PRODUCT-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "product"
    })
    public static class PRODUCTS {

        @XmlElement(name = "PRODUCT", required = true)
        protected List<PRODUCTTYPE> product;

        /**
         * Gets the value of the product property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPRODUCT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PRODUCTTYPE }
         * 
         * 
         */
        public List<PRODUCTTYPE> getPRODUCT() {
            if (product == null) {
                product = new ArrayList<PRODUCTTYPE>();
            }
            return this.product;
        }

    }

}
