//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PROJECT" type="{http://www.asam.net/xml/fbx}PROJECT-TYPE"/>
 *         &lt;element name="PROTOCOLS" type="{http://www.asam.net/xml/fbx}PROTOCOLS" minOccurs="0"/>
 *         &lt;element name="ELEMENTS" type="{http://www.asam.net/xml/fbx}ELEMENTS"/>
 *         &lt;element name="PROCESSING-INFORMATION" type="{http://www.asam.net/xml/fbx}PROCESSING-INFORMATION" minOccurs="0"/>
 *         &lt;element name="REQUIREMENTS" type="{http://www.asam.net/xml/fbx}REQUIREMENTS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="VERSION" use="required" type="{http://www.asam.net/xml/fbx}VERSION-TYPE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "project",
    "protocols",
    "elements",
    "processinginformation",
    "requirements"
})
@XmlRootElement(name = "FIBEX")
public class FIBEX {

    @XmlElement(name = "PROJECT", required = true)
    protected PROJECTTYPE project;
    @XmlElement(name = "PROTOCOLS")
    protected PROTOCOLS protocols;
    @XmlElement(name = "ELEMENTS", required = true)
    protected ELEMENTS elements;
    @XmlElement(name = "PROCESSING-INFORMATION")
    protected PROCESSINGINFORMATION processinginformation;
    @XmlElement(name = "REQUIREMENTS")
    protected REQUIREMENTS requirements;
    @XmlAttribute(name = "VERSION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link PROJECTTYPE }
     *     
     */
    public PROJECTTYPE getPROJECT() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROJECTTYPE }
     *     
     */
    public void setPROJECT(PROJECTTYPE value) {
        this.project = value;
    }

    /**
     * Gets the value of the protocols property.
     * 
     * @return
     *     possible object is
     *     {@link PROTOCOLS }
     *     
     */
    public PROTOCOLS getPROTOCOLS() {
        return protocols;
    }

    /**
     * Sets the value of the protocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROTOCOLS }
     *     
     */
    public void setPROTOCOLS(PROTOCOLS value) {
        this.protocols = value;
    }

    /**
     * Gets the value of the elements property.
     * 
     * @return
     *     possible object is
     *     {@link ELEMENTS }
     *     
     */
    public ELEMENTS getELEMENTS() {
        return elements;
    }

    /**
     * Sets the value of the elements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELEMENTS }
     *     
     */
    public void setELEMENTS(ELEMENTS value) {
        this.elements = value;
    }

    /**
     * Gets the value of the processinginformation property.
     * 
     * @return
     *     possible object is
     *     {@link PROCESSINGINFORMATION }
     *     
     */
    public PROCESSINGINFORMATION getPROCESSINGINFORMATION() {
        return processinginformation;
    }

    /**
     * Sets the value of the processinginformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROCESSINGINFORMATION }
     *     
     */
    public void setPROCESSINGINFORMATION(PROCESSINGINFORMATION value) {
        this.processinginformation = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link REQUIREMENTS }
     *     
     */
    public REQUIREMENTS getREQUIREMENTS() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUIREMENTS }
     *     
     */
    public void setREQUIREMENTS(REQUIREMENTS value) {
        this.requirements = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVERSION() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVERSION(String value) {
        this.version = value;
    }

}
