//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Content model for the entity FRAME-TRIGGERING.
 * 
 * <p>Java class for FRAME-TRIGGERING-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FRAME-TRIGGERING-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TIMINGS" type="{http://www.asam.net/xml/fbx}FRAME-TIMINGS" minOccurs="0"/>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}IDENTIFIER" minOccurs="0"/>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}FRAME-REF"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-FRAME-TRIGGERING-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FRAME-TRIGGERING-TYPE", propOrder = {
    "timings",
    "identifier",
    "frameref",
    "manufacturerextension"
})
public class FRAMETRIGGERINGTYPE {

    @XmlElement(name = "TIMINGS")
    protected FRAMETIMINGS timings;
    @XmlElement(name = "IDENTIFIER")
    protected IDENTIFIER identifier;
    @XmlElement(name = "FRAME-REF", required = true)
    protected FRAMEREF frameref;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERFRAMETRIGGERINGEXTENSION manufacturerextension;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the timings property.
     * 
     * @return
     *     possible object is
     *     {@link FRAMETIMINGS }
     *     
     */
    public FRAMETIMINGS getTIMINGS() {
        return timings;
    }

    /**
     * Sets the value of the timings property.
     * 
     * @param value
     *     allowed object is
     *     {@link FRAMETIMINGS }
     *     
     */
    public void setTIMINGS(FRAMETIMINGS value) {
        this.timings = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IDENTIFIER }
     *     
     */
    public IDENTIFIER getIDENTIFIER() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDENTIFIER }
     *     
     */
    public void setIDENTIFIER(IDENTIFIER value) {
        this.identifier = value;
    }

    /**
     * Refering a frame
     * 
     * @return
     *     possible object is
     *     {@link FRAMEREF }
     *     
     */
    public FRAMEREF getFRAMEREF() {
        return frameref;
    }

    /**
     * Sets the value of the frameref property.
     * 
     * @param value
     *     allowed object is
     *     {@link FRAMEREF }
     *     
     */
    public void setFRAMEREF(FRAMEREF value) {
        this.frameref = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERFRAMETRIGGERINGEXTENSION }
     *     
     */
    public MANUFACTURERFRAMETRIGGERINGEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERFRAMETRIGGERINGEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERFRAMETRIGGERINGEXTENSION value) {
        this.manufacturerextension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
