//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity FRAME. 
 * 
 * <p>Java class for FRAME-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FRAME-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="BYTE-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="FRAME-TYPE" type="{http://www.asam.net/xml/fbx}FRAMETYPE2" minOccurs="0"/>
 *         &lt;element name="PDU-INSTANCES" type="{http://www.asam.net/xml/fbx}PDU-INSTANCES" minOccurs="0"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-FRAME-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FRAME-TYPE", propOrder = {
    "bytelength",
    "frametype",
    "pduinstances",
    "manufacturerextension"
})
public class FRAMETYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "BYTE-LENGTH")
    @XmlSchemaType(name = "unsignedInt")
    protected long bytelength;
    @XmlElement(name = "FRAME-TYPE")
    protected FRAMETYPE2 frametype;
    @XmlElement(name = "PDU-INSTANCES")
    protected PDUINSTANCES pduinstances;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERFRAMEEXTENSION manufacturerextension;

    /**
     * Gets the value of the bytelength property.
     * 
     */
    public long getBYTELENGTH() {
        return bytelength;
    }

    /**
     * Sets the value of the bytelength property.
     * 
     */
    public void setBYTELENGTH(long value) {
        this.bytelength = value;
    }

    /**
     * Gets the value of the frametype property.
     * 
     * @return
     *     possible object is
     *     {@link FRAMETYPE2 }
     *     
     */
    public FRAMETYPE2 getFRAMETYPE() {
        return frametype;
    }

    /**
     * Sets the value of the frametype property.
     * 
     * @param value
     *     allowed object is
     *     {@link FRAMETYPE2 }
     *     
     */
    public void setFRAMETYPE(FRAMETYPE2 value) {
        this.frametype = value;
    }

    /**
     * Gets the value of the pduinstances property.
     * 
     * @return
     *     possible object is
     *     {@link PDUINSTANCES }
     *     
     */
    public PDUINSTANCES getPDUINSTANCES() {
        return pduinstances;
    }

    /**
     * Sets the value of the pduinstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDUINSTANCES }
     *     
     */
    public void setPDUINSTANCES(PDUINSTANCES value) {
        this.pduinstances = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERFRAMEEXTENSION }
     *     
     */
    public MANUFACTURERFRAMEEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERFRAMEEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERFRAMEEXTENSION value) {
        this.manufacturerextension = value;
    }

}
