//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Time behavior of a frame specified in a sequence of cluster specific timing types
 * 
 * <p>Java class for FRAME-TIMINGS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FRAME-TIMINGS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="RELATIVELY-SCHEDULED-TIMING" type="{http://www.asam.net/xml/fbx}RELATIVELY-SCHEDULED-TIMING-TYPE"/>
 *         &lt;element name="ABSOLUTELY-SCHEDULED-TIMING" type="{http://www.asam.net/xml/fbx}ABSOLUTELY-SCHEDULED-TIMING-TYPE"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FRAME-TIMINGS", propOrder = {
    "relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING"
})
public class FRAMETIMINGS {

    @XmlElements({
        @XmlElement(name = "ABSOLUTELY-SCHEDULED-TIMING", type = ABSOLUTELYSCHEDULEDTIMINGTYPE.class),
        @XmlElement(name = "RELATIVELY-SCHEDULED-TIMING", type = RELATIVELYSCHEDULEDTIMINGTYPE.class)
    })
    protected List<Object> relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING;

    /**
     * Gets the value of the relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRELATIVELYSCHEDULEDTIMINGOrABSOLUTELYSCHEDULEDTIMING().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ABSOLUTELYSCHEDULEDTIMINGTYPE }
     * {@link RELATIVELYSCHEDULEDTIMINGTYPE }
     * 
     * 
     */
    public List<Object> getRELATIVELYSCHEDULEDTIMINGOrABSOLUTELYSCHEDULEDTIMING() {
        if (relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING == null) {
            relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING = new ArrayList<Object>();
        }
        return this.relativelyscheduledtimingOrABSOLUTELYSCHEDULEDTIMING;
    }

}
