//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity FUNCTION.
 * 
 * <p>Java class for FUNCTION-REQ-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FUNCTION-REQ-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FUNCTION-REFS" type="{http://www.asam.net/xml/fbx}FUNCTION-REFS"/>
 *         &lt;element name="CYCLE-PERIOD" type="{http://www.asam.net/xml/fbx}TIME-RANGE-TYPE" minOccurs="0"/>
 *         &lt;element name="CYCLE-OFFSET" type="{http://www.asam.net/xml/fbx}TIME-RANGE-TYPE" minOccurs="0"/>
 *         &lt;element name="W-C-E-T" type="{http://www.asam.net/xml/fbx}TIME-RANGE-TYPE" minOccurs="0"/>
 *         &lt;element name="DEADLINE" type="{http://www.asam.net/xml/fbx}TIME-RANGE-TYPE" minOccurs="0"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-FUNCTION-REQ-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FUNCTION-REQ-TYPE", propOrder = {
    "functionrefs",
    "cycleperiod",
    "cycleoffset",
    "wcet",
    "deadline",
    "manufacturerextension"
})
public class FUNCTIONREQTYPE {

    @XmlElement(name = "FUNCTION-REFS", required = true)
    protected FUNCTIONREFS functionrefs;
    @XmlElement(name = "CYCLE-PERIOD")
    protected TIMERANGETYPE cycleperiod;
    @XmlElement(name = "CYCLE-OFFSET")
    protected TIMERANGETYPE cycleoffset;
    @XmlElement(name = "W-C-E-T")
    protected TIMERANGETYPE wcet;
    @XmlElement(name = "DEADLINE")
    protected TIMERANGETYPE deadline;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERFUNCTIONREQEXTENSION manufacturerextension;

    /**
     * Gets the value of the functionrefs property.
     * 
     * @return
     *     possible object is
     *     {@link FUNCTIONREFS }
     *     
     */
    public FUNCTIONREFS getFUNCTIONREFS() {
        return functionrefs;
    }

    /**
     * Sets the value of the functionrefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link FUNCTIONREFS }
     *     
     */
    public void setFUNCTIONREFS(FUNCTIONREFS value) {
        this.functionrefs = value;
    }

    /**
     * Gets the value of the cycleperiod property.
     * 
     * @return
     *     possible object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public TIMERANGETYPE getCYCLEPERIOD() {
        return cycleperiod;
    }

    /**
     * Sets the value of the cycleperiod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public void setCYCLEPERIOD(TIMERANGETYPE value) {
        this.cycleperiod = value;
    }

    /**
     * Gets the value of the cycleoffset property.
     * 
     * @return
     *     possible object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public TIMERANGETYPE getCYCLEOFFSET() {
        return cycleoffset;
    }

    /**
     * Sets the value of the cycleoffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public void setCYCLEOFFSET(TIMERANGETYPE value) {
        this.cycleoffset = value;
    }

    /**
     * Gets the value of the wcet property.
     * 
     * @return
     *     possible object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public TIMERANGETYPE getWCET() {
        return wcet;
    }

    /**
     * Sets the value of the wcet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public void setWCET(TIMERANGETYPE value) {
        this.wcet = value;
    }

    /**
     * Gets the value of the deadline property.
     * 
     * @return
     *     possible object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public TIMERANGETYPE getDEADLINE() {
        return deadline;
    }

    /**
     * Sets the value of the deadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIMERANGETYPE }
     *     
     */
    public void setDEADLINE(TIMERANGETYPE value) {
        this.deadline = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERFUNCTIONREQEXTENSION }
     *     
     */
    public MANUFACTURERFUNCTIONREQEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERFUNCTIONREQEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERFUNCTIONREQEXTENSION value) {
        this.manufacturerextension = value;
    }

}
