//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity FUNCTION. 
 * 
 * <p>Java class for FUNCTION-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FUNCTION-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="INPUT-PORTS" type="{http://www.asam.net/xml/fbx}FUNCTION-INPUT-PORTS" minOccurs="0"/>
 *         &lt;element name="OUTPUT-PORTS" type="{http://www.asam.net/xml/fbx}FUNCTION-OUTPUT-PORTS" minOccurs="0"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-FUNCTION-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FUNCTION-TYPE", propOrder = {
    "inputports",
    "outputports",
    "manufacturerextension"
})
public class FUNCTIONTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "INPUT-PORTS")
    protected FUNCTIONINPUTPORTS inputports;
    @XmlElement(name = "OUTPUT-PORTS")
    protected FUNCTIONOUTPUTPORTS outputports;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERFUNCTIONEXTENSION manufacturerextension;

    /**
     * Gets the value of the inputports property.
     * 
     * @return
     *     possible object is
     *     {@link FUNCTIONINPUTPORTS }
     *     
     */
    public FUNCTIONINPUTPORTS getINPUTPORTS() {
        return inputports;
    }

    /**
     * Sets the value of the inputports property.
     * 
     * @param value
     *     allowed object is
     *     {@link FUNCTIONINPUTPORTS }
     *     
     */
    public void setINPUTPORTS(FUNCTIONINPUTPORTS value) {
        this.inputports = value;
    }

    /**
     * Gets the value of the outputports property.
     * 
     * @return
     *     possible object is
     *     {@link FUNCTIONOUTPUTPORTS }
     *     
     */
    public FUNCTIONOUTPUTPORTS getOUTPUTPORTS() {
        return outputports;
    }

    /**
     * Sets the value of the outputports property.
     * 
     * @param value
     *     allowed object is
     *     {@link FUNCTIONOUTPUTPORTS }
     *     
     */
    public void setOUTPUTPORTS(FUNCTIONOUTPUTPORTS value) {
        this.outputports = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERFUNCTIONEXTENSION }
     *     
     */
    public MANUFACTURERFUNCTIONEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERFUNCTIONEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERFUNCTIONEXTENSION value) {
        this.manufacturerextension = value;
    }

}
