//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity GATEWAY. Platform-specific extensions are not allowed, to maintain the capability to describe multi-platform networks.
 * 
 * <p>Java class for GATEWAY-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GATEWAY-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}ECU-REF"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-GATEWAY-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GATEWAY-TYPE", propOrder = {
    "ecuref",
    "manufacturerextension"
})
public class GATEWAYTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "ECU-REF", required = true)
    protected ECUREF ecuref;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERGATEWAYEXTENSION manufacturerextension;

    /**
     * Gets the value of the ecuref property.
     * 
     * @return
     *     possible object is
     *     {@link ECUREF }
     *     
     */
    public ECUREF getECUREF() {
        return ecuref;
    }

    /**
     * Sets the value of the ecuref property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECUREF }
     *     
     */
    public void setECUREF(ECUREF value) {
        this.ecuref = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERGATEWAYEXTENSION }
     *     
     */
    public MANUFACTURERGATEWAYEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERGATEWAYEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERGATEWAYEXTENSION value) {
        this.manufacturerextension = value;
    }

}
