//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="IDENTIFIER-VALUE" type="{http://www.asam.net/xml/fbx}IDENTIFIER-VALUE-TYPE"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-IDENTIFIER-EXTENSION" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifiervalue",
    "manufacturerextension"
})
@XmlRootElement(name = "IDENTIFIER")
public class IDENTIFIER {

    @XmlElement(name = "IDENTIFIER-VALUE")
    protected IDENTIFIERVALUETYPE identifiervalue;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERIDENTIFIEREXTENSION manufacturerextension;

    /**
     * Gets the value of the identifiervalue property.
     * 
     * @return
     *     possible object is
     *     {@link IDENTIFIERVALUETYPE }
     *     
     */
    public IDENTIFIERVALUETYPE getIDENTIFIERVALUE() {
        return identifiervalue;
    }

    /**
     * Sets the value of the identifiervalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDENTIFIERVALUETYPE }
     *     
     */
    public void setIDENTIFIERVALUE(IDENTIFIERVALUETYPE value) {
        this.identifiervalue = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERIDENTIFIEREXTENSION }
     *     
     */
    public MANUFACTURERIDENTIFIEREXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERIDENTIFIEREXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERIDENTIFIEREXTENSION value) {
        this.manufacturerextension = value;
    }

}
