//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * SIGNALs within a referenced PDU
 * 
 * <p>Java class for INCLUDED-PDU-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INCLUDED-PDU-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}PDU-TRIGGERING-REF"/>
 *         &lt;choice>
 *           &lt;element name="INCLUDED-SIGNALS" type="{http://www.asam.net/xml/fbx}INCLUDED-SIGNALS"/>
 *           &lt;element name="COMPLETE-PDU">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INCLUDED-PDU-TYPE", propOrder = {
    "pdutriggeringref",
    "includedsignals",
    "completepdu"
})
public class INCLUDEDPDUTYPE {

    @XmlElement(name = "PDU-TRIGGERING-REF", required = true)
    protected PDUTRIGGERINGREF pdutriggeringref;
    @XmlElement(name = "INCLUDED-SIGNALS")
    protected INCLUDEDSIGNALS includedsignals;
    @XmlElement(name = "COMPLETE-PDU")
    protected INCLUDEDPDUTYPE.COMPLETEPDU completepdu;

    /**
     * Gets the value of the pdutriggeringref property.
     * 
     * @return
     *     possible object is
     *     {@link PDUTRIGGERINGREF }
     *     
     */
    public PDUTRIGGERINGREF getPDUTRIGGERINGREF() {
        return pdutriggeringref;
    }

    /**
     * Sets the value of the pdutriggeringref property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDUTRIGGERINGREF }
     *     
     */
    public void setPDUTRIGGERINGREF(PDUTRIGGERINGREF value) {
        this.pdutriggeringref = value;
    }

    /**
     * Gets the value of the includedsignals property.
     * 
     * @return
     *     possible object is
     *     {@link INCLUDEDSIGNALS }
     *     
     */
    public INCLUDEDSIGNALS getINCLUDEDSIGNALS() {
        return includedsignals;
    }

    /**
     * Sets the value of the includedsignals property.
     * 
     * @param value
     *     allowed object is
     *     {@link INCLUDEDSIGNALS }
     *     
     */
    public void setINCLUDEDSIGNALS(INCLUDEDSIGNALS value) {
        this.includedsignals = value;
    }

    /**
     * Gets the value of the completepdu property.
     * 
     * @return
     *     possible object is
     *     {@link INCLUDEDPDUTYPE.COMPLETEPDU }
     *     
     */
    public INCLUDEDPDUTYPE.COMPLETEPDU getCOMPLETEPDU() {
        return completepdu;
    }

    /**
     * Sets the value of the completepdu property.
     * 
     * @param value
     *     allowed object is
     *     {@link INCLUDEDPDUTYPE.COMPLETEPDU }
     *     
     */
    public void setCOMPLETEPDU(INCLUDEDPDUTYPE.COMPLETEPDU value) {
        this.completepdu = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class COMPLETEPDU {


    }

}
