//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Selected SIGNALs within the referenced PDU
 * 
 * <p>Java class for INCLUDED-SIGNALS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INCLUDED-SIGNALS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INCLUDED-SIGNAL" type="{http://www.asam.net/xml/fbx}INCLUDED-SIGNAL-TYPE" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INCLUDED-SIGNALS", propOrder = {
    "includedsignal"
})
public class INCLUDEDSIGNALS {

    @XmlElement(name = "INCLUDED-SIGNAL", required = true)
    protected List<INCLUDEDSIGNALTYPE> includedsignal;

    /**
     * Gets the value of the includedsignal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includedsignal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINCLUDEDSIGNAL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link INCLUDEDSIGNALTYPE }
     * 
     * 
     */
    public List<INCLUDEDSIGNALTYPE> getINCLUDEDSIGNAL() {
        if (includedsignal == null) {
            includedsignal = new ArrayList<INCLUDEDSIGNALTYPE>();
        }
        return this.includedsignal;
    }

}
