//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * For reusability an intervals content model is specified using a type definition (according to the ASAM convention)
 * 
 * <p>Java class for INTERVAL-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="INTERVAL-TYPE">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *       &lt;attribute name="INTERVAL-TYPE" default="CLOSED">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="OPEN"/>
 *             &lt;enumeration value="CLOSED"/>
 *             &lt;enumeration value="INFINITE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "INTERVAL-TYPE", namespace = "http://www.asam.net/xml", propOrder = {
    "value"
})
public class INTERVALTYPE {

    @XmlValue
    protected double value;
    @XmlAttribute(name = "INTERVAL-TYPE")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String intervaltype;

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the intervaltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINTERVALTYPE() {
        if (intervaltype == null) {
            return "CLOSED";
        } else {
            return intervaltype;
        }
    }

    /**
     * Sets the value of the intervaltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINTERVALTYPE(String value) {
        this.intervaltype = value;
    }

}
