//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity MULTIPLEXER.
 * 
 * <p>Java class for MULTIPLEXER-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MULTIPLEXER-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SWITCH" type="{http://www.asam.net/xml/fbx}SWITCH"/>
 *         &lt;element name="DYNAMIC-PART" type="{http://www.asam.net/xml/fbx}DYNAMIC-PART"/>
 *         &lt;element name="STATIC-PART" type="{http://www.asam.net/xml/fbx}STATIC-PART" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="EXTENDED-ADDRESSING" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MULTIPLEXER-TYPE", propOrder = {
    "_switch",
    "dynamicpart",
    "staticpart"
})
public class MULTIPLEXERTYPE {

    @XmlElement(name = "SWITCH", required = true)
    protected SWITCH _switch;
    @XmlElement(name = "DYNAMIC-PART", required = true)
    protected DYNAMICPART dynamicpart;
    @XmlElement(name = "STATIC-PART")
    protected STATICPART staticpart;
    @XmlAttribute(name = "EXTENDED-ADDRESSING")
    protected Boolean extendedaddressing;

    /**
     * Gets the value of the switch property.
     * 
     * @return
     *     possible object is
     *     {@link SWITCH }
     *     
     */
    public SWITCH getSWITCH() {
        return _switch;
    }

    /**
     * Sets the value of the switch property.
     * 
     * @param value
     *     allowed object is
     *     {@link SWITCH }
     *     
     */
    public void setSWITCH(SWITCH value) {
        this._switch = value;
    }

    /**
     * Gets the value of the dynamicpart property.
     * 
     * @return
     *     possible object is
     *     {@link DYNAMICPART }
     *     
     */
    public DYNAMICPART getDYNAMICPART() {
        return dynamicpart;
    }

    /**
     * Sets the value of the dynamicpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link DYNAMICPART }
     *     
     */
    public void setDYNAMICPART(DYNAMICPART value) {
        this.dynamicpart = value;
    }

    /**
     * Gets the value of the staticpart property.
     * 
     * @return
     *     possible object is
     *     {@link STATICPART }
     *     
     */
    public STATICPART getSTATICPART() {
        return staticpart;
    }

    /**
     * Sets the value of the staticpart property.
     * 
     * @param value
     *     allowed object is
     *     {@link STATICPART }
     *     
     */
    public void setSTATICPART(STATICPART value) {
        this.staticpart = value;
    }

    /**
     * Gets the value of the extendedaddressing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEXTENDEDADDRESSING() {
        if (extendedaddressing == null) {
            return true;
        } else {
            return extendedaddressing;
        }
    }

    /**
     * Sets the value of the extendedaddressing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEXTENDEDADDRESSING(Boolean value) {
        this.extendedaddressing = value;
    }

}
