//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity PDU-INSTANCE.
 * 
 * <p>Java class for PDU-INSTANCE-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDU-INSTANCE-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}GENERIC-PDU-INSTANCE-TYPE">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.asam.net/xml/fbx}COMMON-LAYOUT-DETAILS"/>
 *         &lt;element name="PDU-UPDATE-BIT-POSITION" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDU-INSTANCE-TYPE", propOrder = {
    "bitposition",
    "ishighlowbyteorder",
    "sequencenumber",
    "pduupdatebitposition"
})
public class PDUINSTANCETYPE
    extends GENERICPDUINSTANCETYPE
{

    @XmlElement(name = "BIT-POSITION")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer bitposition;
    @XmlElement(name = "IS-HIGH-LOW-BYTE-ORDER")
    protected Boolean ishighlowbyteorder;
    @XmlElement(name = "SEQUENCE-NUMBER")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer sequencenumber;
    @XmlElement(name = "PDU-UPDATE-BIT-POSITION")
    @XmlSchemaType(name = "unsignedInt")
    protected Long pduupdatebitposition;

    /**
     * Gets the value of the bitposition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBITPOSITION() {
        return bitposition;
    }

    /**
     * Sets the value of the bitposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBITPOSITION(Integer value) {
        this.bitposition = value;
    }

    /**
     * Gets the value of the ishighlowbyteorder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISHIGHLOWBYTEORDER() {
        return ishighlowbyteorder;
    }

    /**
     * Sets the value of the ishighlowbyteorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISHIGHLOWBYTEORDER(Boolean value) {
        this.ishighlowbyteorder = value;
    }

    /**
     * Gets the value of the sequencenumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSEQUENCENUMBER() {
        return sequencenumber;
    }

    /**
     * Sets the value of the sequencenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSEQUENCENUMBER(Integer value) {
        this.sequencenumber = value;
    }

    /**
     * Gets the value of the pduupdatebitposition property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPDUUPDATEBITPOSITION() {
        return pduupdatebitposition;
    }

    /**
     * Sets the value of the pduupdatebitposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPDUUPDATEBITPOSITION(Long value) {
        this.pduupdatebitposition = value;
    }

}
