//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity PDU-REQUIREMENT
 * 
 * <p>Java class for PDU-REQ-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDU-REQ-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}ECU-REF" maxOccurs="unbounded"/>
 *         &lt;choice>
 *           &lt;element name="OUTPUT" type="{http://www.asam.net/xml/fbx}PDU-REQ-DIRECTION-TYPE"/>
 *           &lt;sequence>
 *             &lt;element name="INPUT" type="{http://www.asam.net/xml/fbx}PDU-REQ-DIRECTION-TYPE"/>
 *             &lt;element name="OUTPUT" type="{http://www.asam.net/xml/fbx}PDU-REQ-DIRECTION-TYPE" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDU-REQ-TYPE", propOrder = {
    "content"
})
public class PDUREQTYPE {

    @XmlElementRefs({
        @XmlElementRef(name = "OUTPUT", namespace = "http://www.asam.net/xml/fbx", type = JAXBElement.class),
        @XmlElementRef(name = "INPUT", namespace = "http://www.asam.net/xml/fbx", type = JAXBElement.class),
        @XmlElementRef(name = "ECU-REF", namespace = "http://www.asam.net/xml/fbx", type = ECUREF.class)
    })
    protected List<Object> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "OUTPUT" is used by two different parts of a schema. See: 
     * line 1160 of file:/C:/thomas/workspace/ConfigTest/src/fibex.xsd
     * line 1157 of file:/C:/thomas/workspace/ConfigTest/src/fibex.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PDUREQDIRECTIONTYPE }{@code >}
     * {@link ECUREF }
     * {@link JAXBElement }{@code <}{@link PDUREQDIRECTIONTYPE }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
