//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Content model for the entity PDU-TRIGGERING.
 * 
 * <p>Java class for PDU-TRIGGERING-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDU-TRIGGERING-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TIMINGS" type="{http://www.asam.net/xml/fbx}PDU-TIMINGS" minOccurs="0"/>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}PDU-REF"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-PDU-TRIGGERING-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDU-TRIGGERING-TYPE", propOrder = {
    "timings",
    "pduref",
    "manufacturerextension"
})
public class PDUTRIGGERINGTYPE {

    @XmlElement(name = "TIMINGS")
    protected PDUTIMINGS timings;
    @XmlElement(name = "PDU-REF", required = true)
    protected PDUREF pduref;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERPDUTRIGGERINGEXTENSION manufacturerextension;
    @XmlAttribute(name = "ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the timings property.
     * 
     * @return
     *     possible object is
     *     {@link PDUTIMINGS }
     *     
     */
    public PDUTIMINGS getTIMINGS() {
        return timings;
    }

    /**
     * Sets the value of the timings property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDUTIMINGS }
     *     
     */
    public void setTIMINGS(PDUTIMINGS value) {
        this.timings = value;
    }

    /**
     * Refering a frame
     * 
     * @return
     *     possible object is
     *     {@link PDUREF }
     *     
     */
    public PDUREF getPDUREF() {
        return pduref;
    }

    /**
     * Sets the value of the pduref property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDUREF }
     *     
     */
    public void setPDUREF(PDUREF value) {
        this.pduref = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERPDUTRIGGERINGEXTENSION }
     *     
     */
    public MANUFACTURERPDUTRIGGERINGEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERPDUTRIGGERINGEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERPDUTRIGGERINGEXTENSION value) {
        this.manufacturerextension = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
