//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Time behavior of a PDU specified in a sequence of cluster specific timing types
 * 
 * <p>Java class for PDU-TIMINGS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDU-TIMINGS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="CYCLIC-TIMING" type="{http://www.asam.net/xml/fbx}CYCLIC-TIMING-TYPE"/>
 *         &lt;element name="EVENT-CONTROLLED-TIMING" type="{http://www.asam.net/xml/fbx}EVENT-CONTROLLED-TIMING-TYPE"/>
 *         &lt;element name="REQUEST-CONTROLLED-TIMING" type="{http://www.asam.net/xml/fbx}REQUEST-CONTROLLED-TIMING-TYPE"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDU-TIMINGS", propOrder = {
    "cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING"
})
public class PDUTIMINGS {

    @XmlElements({
        @XmlElement(name = "EVENT-CONTROLLED-TIMING", type = EVENTCONTROLLEDTIMINGTYPE.class),
        @XmlElement(name = "REQUEST-CONTROLLED-TIMING", type = REQUESTCONTROLLEDTIMINGTYPE.class),
        @XmlElement(name = "CYCLIC-TIMING", type = CYCLICTIMINGTYPE.class)
    })
    protected List<Object> cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING;

    /**
     * Gets the value of the cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCYCLICTIMINGOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EVENTCONTROLLEDTIMINGTYPE }
     * {@link REQUESTCONTROLLEDTIMINGTYPE }
     * {@link CYCLICTIMINGTYPE }
     * 
     * 
     */
    public List<Object> getCYCLICTIMINGOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING() {
        if (cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING == null) {
            cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING = new ArrayList<Object>();
        }
        return this.cyclictimingOrEVENTCONTROLLEDTIMINGOrREQUESTCONTROLLEDTIMING;
    }

}
