//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity PDU. 
 * 
 * <p>Java class for PDU-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PDU-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="BYTE-LENGTH" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="PDU-TYPE" type="{http://www.asam.net/xml/fbx}PDUTYPE2"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="SIGNAL-INSTANCES" type="{http://www.asam.net/xml/fbx}SIGNAL-INSTANCES"/>
 *           &lt;element name="MULTIPLEXER" type="{http://www.asam.net/xml/fbx}MULTIPLEXER-TYPE" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-PDU-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PDU-TYPE", propOrder = {
    "bytelength",
    "pdutype",
    "signalinstances",
    "multiplexer",
    "manufacturerextension"
})
public class PDUTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "BYTE-LENGTH")
    @XmlSchemaType(name = "unsignedInt")
    protected long bytelength;
    @XmlElement(name = "PDU-TYPE", required = true)
    protected PDUTYPE2 pdutype;
    @XmlElement(name = "SIGNAL-INSTANCES")
    protected SIGNALINSTANCES signalinstances;
    @XmlElement(name = "MULTIPLEXER")
    protected List<MULTIPLEXERTYPE> multiplexer;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERPDUEXTENSION manufacturerextension;

    /**
     * Gets the value of the bytelength property.
     * 
     */
    public long getBYTELENGTH() {
        return bytelength;
    }

    /**
     * Sets the value of the bytelength property.
     * 
     */
    public void setBYTELENGTH(long value) {
        this.bytelength = value;
    }

    /**
     * Gets the value of the pdutype property.
     * 
     * @return
     *     possible object is
     *     {@link PDUTYPE2 }
     *     
     */
    public PDUTYPE2 getPDUTYPE() {
        return pdutype;
    }

    /**
     * Sets the value of the pdutype property.
     * 
     * @param value
     *     allowed object is
     *     {@link PDUTYPE2 }
     *     
     */
    public void setPDUTYPE(PDUTYPE2 value) {
        this.pdutype = value;
    }

    /**
     * Gets the value of the signalinstances property.
     * 
     * @return
     *     possible object is
     *     {@link SIGNALINSTANCES }
     *     
     */
    public SIGNALINSTANCES getSIGNALINSTANCES() {
        return signalinstances;
    }

    /**
     * Sets the value of the signalinstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGNALINSTANCES }
     *     
     */
    public void setSIGNALINSTANCES(SIGNALINSTANCES value) {
        this.signalinstances = value;
    }

    /**
     * Gets the value of the multiplexer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multiplexer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMULTIPLEXER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MULTIPLEXERTYPE }
     * 
     * 
     */
    public List<MULTIPLEXERTYPE> getMULTIPLEXER() {
        if (multiplexer == null) {
            multiplexer = new ArrayList<MULTIPLEXERTYPE>();
        }
        return this.multiplexer;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERPDUEXTENSION }
     *     
     */
    public MANUFACTURERPDUEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERPDUEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERPDUEXTENSION value) {
        this.manufacturerextension = value;
    }

}
