//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * All ports affected by this requirement.
 * 
 * <p>Java class for PORT-REFS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PORT-REFS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="FUNC-INPUT-PORT-REF" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FUNC-OUTPUT-PORT-REF" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ECU-INPUT-PORT-REF" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PORT-REFS", propOrder = {
    "funcinputportref",
    "funcoutputportref",
    "ecuinputportref"
})
public class PORTREFS {

    @XmlElement(name = "FUNC-INPUT-PORT-REF")
    protected List<PORTREFS.FUNCINPUTPORTREF> funcinputportref;
    @XmlElement(name = "FUNC-OUTPUT-PORT-REF")
    protected List<PORTREFS.FUNCOUTPUTPORTREF> funcoutputportref;
    @XmlElement(name = "ECU-INPUT-PORT-REF")
    protected List<PORTREFS.ECUINPUTPORTREF> ecuinputportref;

    /**
     * Gets the value of the funcinputportref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the funcinputportref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFUNCINPUTPORTREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PORTREFS.FUNCINPUTPORTREF }
     * 
     * 
     */
    public List<PORTREFS.FUNCINPUTPORTREF> getFUNCINPUTPORTREF() {
        if (funcinputportref == null) {
            funcinputportref = new ArrayList<PORTREFS.FUNCINPUTPORTREF>();
        }
        return this.funcinputportref;
    }

    /**
     * Gets the value of the funcoutputportref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the funcoutputportref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFUNCOUTPUTPORTREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PORTREFS.FUNCOUTPUTPORTREF }
     * 
     * 
     */
    public List<PORTREFS.FUNCOUTPUTPORTREF> getFUNCOUTPUTPORTREF() {
        if (funcoutputportref == null) {
            funcoutputportref = new ArrayList<PORTREFS.FUNCOUTPUTPORTREF>();
        }
        return this.funcoutputportref;
    }

    /**
     * Gets the value of the ecuinputportref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ecuinputportref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getECUINPUTPORTREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PORTREFS.ECUINPUTPORTREF }
     * 
     * 
     */
    public List<PORTREFS.ECUINPUTPORTREF> getECUINPUTPORTREF() {
        if (ecuinputportref == null) {
            ecuinputportref = new ArrayList<PORTREFS.ECUINPUTPORTREF>();
        }
        return this.ecuinputportref;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ECUINPUTPORTREF {

        @XmlAttribute(name = "ID-REF", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object idref;

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIDREF() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIDREF(Object value) {
            this.idref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FUNCINPUTPORTREF {

        @XmlAttribute(name = "ID-REF", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object idref;

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIDREF() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIDREF(Object value) {
            this.idref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FUNCOUTPUTPORTREF {

        @XmlAttribute(name = "ID-REF", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object idref;

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIDREF() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIDREF(Object value) {
            this.idref = value;
        }

    }

}
