//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data needed to process data in elements.
 * 
 * <p>Java class for PROCESSING-INFORMATION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROCESSING-INFORMATION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml}UNIT-SPEC" minOccurs="0"/>
 *         &lt;element name="CODINGS" type="{http://www.asam.net/xml/fbx}CODINGS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROCESSING-INFORMATION", propOrder = {
    "unitspec",
    "codings"
})
public class PROCESSINGINFORMATION {

    @XmlElement(name = "UNIT-SPEC", namespace = "http://www.asam.net/xml")
    protected UNITSPEC unitspec;
    @XmlElement(name = "CODINGS")
    protected CODINGS codings;

    /**
     * Gets the value of the unitspec property.
     * 
     * @return
     *     possible object is
     *     {@link UNITSPEC }
     *     
     */
    public UNITSPEC getUNITSPEC() {
        return unitspec;
    }

    /**
     * Sets the value of the unitspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNITSPEC }
     *     
     */
    public void setUNITSPEC(UNITSPEC value) {
        this.unitspec = value;
    }

    /**
     * Gets the value of the codings property.
     * 
     * @return
     *     possible object is
     *     {@link CODINGS }
     *     
     */
    public CODINGS getCODINGS() {
        return codings;
    }

    /**
     * Sets the value of the codings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODINGS }
     *     
     */
    public void setCODINGS(CODINGS value) {
        this.codings = value;
    }

}
