//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity PROJECT. Platform-specific extensions are not possible, to maintain the capability to describe multi-platform networks.
 * 
 * <p>Java class for PROJECT-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROJECT-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}NAMED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}EXTENT" minOccurs="0"/>
 *         &lt;element ref="{http://www.asam.net/xml}ADMIN-DATA" minOccurs="0"/>
 *         &lt;element ref="{http://www.asam.net/xml}COMPANIES-DATA" minOccurs="0"/>
 *         &lt;element name="FIBEX-COMPANIES-DATA" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FIBEX-COMPANY-DATA" type="{http://www.asam.net/xml/fbx}FIBEX-COMPANY-DATA" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-PROJECT-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROJECT-TYPE", propOrder = {
    "extent",
    "admindata",
    "companiesdata",
    "fibexcompaniesdata",
    "manufacturerextension"
})
public class PROJECTTYPE
    extends NAMEDELEMENTTYPE
{

    @XmlElement(name = "EXTENT")
    protected EXTENT extent;
    @XmlElement(name = "ADMIN-DATA", namespace = "http://www.asam.net/xml")
    protected ADMINDATA admindata;
    @XmlElement(name = "COMPANIES-DATA", namespace = "http://www.asam.net/xml")
    protected COMPANIESDATA companiesdata;
    @XmlElement(name = "FIBEX-COMPANIES-DATA")
    protected PROJECTTYPE.FIBEXCOMPANIESDATA fibexcompaniesdata;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERPROJECTEXTENSION manufacturerextension;

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link EXTENT }
     *     
     */
    public EXTENT getEXTENT() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXTENT }
     *     
     */
    public void setEXTENT(EXTENT value) {
        this.extent = value;
    }

    /**
     * Containing document management information
     * 
     * @return
     *     possible object is
     *     {@link ADMINDATA }
     *     
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADMINDATA }
     *     
     */
    public void setADMINDATA(ADMINDATA value) {
        this.admindata = value;
    }

    /**
     * Collecting the companies involved in project
     * 
     * @return
     *     possible object is
     *     {@link COMPANIESDATA }
     *     
     */
    public COMPANIESDATA getCOMPANIESDATA() {
        return companiesdata;
    }

    /**
     * Sets the value of the companiesdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link COMPANIESDATA }
     *     
     */
    public void setCOMPANIESDATA(COMPANIESDATA value) {
        this.companiesdata = value;
    }

    /**
     * Gets the value of the fibexcompaniesdata property.
     * 
     * @return
     *     possible object is
     *     {@link PROJECTTYPE.FIBEXCOMPANIESDATA }
     *     
     */
    public PROJECTTYPE.FIBEXCOMPANIESDATA getFIBEXCOMPANIESDATA() {
        return fibexcompaniesdata;
    }

    /**
     * Sets the value of the fibexcompaniesdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROJECTTYPE.FIBEXCOMPANIESDATA }
     *     
     */
    public void setFIBEXCOMPANIESDATA(PROJECTTYPE.FIBEXCOMPANIESDATA value) {
        this.fibexcompaniesdata = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERPROJECTEXTENSION }
     *     
     */
    public MANUFACTURERPROJECTEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERPROJECTEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERPROJECTEXTENSION value) {
        this.manufacturerextension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FIBEX-COMPANY-DATA" type="{http://www.asam.net/xml/fbx}FIBEX-COMPANY-DATA" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fibexcompanydata"
    })
    public static class FIBEXCOMPANIESDATA {

        @XmlElement(name = "FIBEX-COMPANY-DATA", required = true)
        protected List<FIBEXCOMPANYDATA> fibexcompanydata;

        /**
         * Gets the value of the fibexcompanydata property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fibexcompanydata property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFIBEXCOMPANYDATA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FIBEXCOMPANYDATA }
         * 
         * 
         */
        public List<FIBEXCOMPANYDATA> getFIBEXCOMPANYDATA() {
            if (fibexcompanydata == null) {
                fibexcompanydata = new ArrayList<FIBEXCOMPANYDATA>();
            }
            return this.fibexcompanydata;
        }

    }

}
