//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Root of all higher level protocol elements
 * 
 * <p>Java class for PROTOCOLS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PROTOCOLS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NM-CONFIGS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.asam.net/xml/fbx}EXTENT" minOccurs="0"/>
 *                   &lt;element name="NM-CONFIG" type="{http://www.asam.net/xml/fbx}NM-CONFIG-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TP-CONFIGS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.asam.net/xml/fbx}EXTENT" minOccurs="0"/>
 *                   &lt;element name="TP-CONFIG" type="{http://www.asam.net/xml/fbx}TP-CONFIG-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PROTOCOLS", propOrder = {
    "nmconfigs",
    "tpconfigs"
})
public class PROTOCOLS {

    @XmlElement(name = "NM-CONFIGS")
    protected PROTOCOLS.NMCONFIGS nmconfigs;
    @XmlElement(name = "TP-CONFIGS")
    protected PROTOCOLS.TPCONFIGS tpconfigs;

    /**
     * Gets the value of the nmconfigs property.
     * 
     * @return
     *     possible object is
     *     {@link PROTOCOLS.NMCONFIGS }
     *     
     */
    public PROTOCOLS.NMCONFIGS getNMCONFIGS() {
        return nmconfigs;
    }

    /**
     * Sets the value of the nmconfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROTOCOLS.NMCONFIGS }
     *     
     */
    public void setNMCONFIGS(PROTOCOLS.NMCONFIGS value) {
        this.nmconfigs = value;
    }

    /**
     * Gets the value of the tpconfigs property.
     * 
     * @return
     *     possible object is
     *     {@link PROTOCOLS.TPCONFIGS }
     *     
     */
    public PROTOCOLS.TPCONFIGS getTPCONFIGS() {
        return tpconfigs;
    }

    /**
     * Sets the value of the tpconfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PROTOCOLS.TPCONFIGS }
     *     
     */
    public void setTPCONFIGS(PROTOCOLS.TPCONFIGS value) {
        this.tpconfigs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}EXTENT" minOccurs="0"/>
     *         &lt;element name="NM-CONFIG" type="{http://www.asam.net/xml/fbx}NM-CONFIG-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "extent",
        "nmconfig"
    })
    public static class NMCONFIGS {

        @XmlElement(name = "EXTENT")
        protected EXTENT extent;
        @XmlElement(name = "NM-CONFIG", required = true)
        protected List<NMCONFIGTYPE> nmconfig;

        /**
         * Gets the value of the extent property.
         * 
         * @return
         *     possible object is
         *     {@link EXTENT }
         *     
         */
        public EXTENT getEXTENT() {
            return extent;
        }

        /**
         * Sets the value of the extent property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXTENT }
         *     
         */
        public void setEXTENT(EXTENT value) {
            this.extent = value;
        }

        /**
         * Gets the value of the nmconfig property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nmconfig property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNMCONFIG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NMCONFIGTYPE }
         * 
         * 
         */
        public List<NMCONFIGTYPE> getNMCONFIG() {
            if (nmconfig == null) {
                nmconfig = new ArrayList<NMCONFIGTYPE>();
            }
            return this.nmconfig;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml/fbx}EXTENT" minOccurs="0"/>
     *         &lt;element name="TP-CONFIG" type="{http://www.asam.net/xml/fbx}TP-CONFIG-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "extent",
        "tpconfig"
    })
    public static class TPCONFIGS {

        @XmlElement(name = "EXTENT")
        protected EXTENT extent;
        @XmlElement(name = "TP-CONFIG", required = true)
        protected List<TPCONFIGTYPE> tpconfig;

        /**
         * Gets the value of the extent property.
         * 
         * @return
         *     possible object is
         *     {@link EXTENT }
         *     
         */
        public EXTENT getEXTENT() {
            return extent;
        }

        /**
         * Sets the value of the extent property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXTENT }
         *     
         */
        public void setEXTENT(EXTENT value) {
            this.extent = value;
        }

        /**
         * Gets the value of the tpconfig property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tpconfig property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTPCONFIG().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPCONFIGTYPE }
         * 
         * 
         */
        public List<TPCONFIGTYPE> getTPCONFIG() {
            if (tpconfig == null) {
                tpconfig = new ArrayList<TPCONFIGTYPE>();
            }
            return this.tpconfig;
        }

    }

}
