//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Root of all requirements
 * 
 * <p>Java class for REQUIREMENTS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REQUIREMENTS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PORT-REQS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PORT-REQ" type="{http://www.asam.net/xml/fbx}PORT-REQ-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FUNCTION-REQS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FUNCTION-REQ" type="{http://www.asam.net/xml/fbx}FUNCTION-REQ-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SIGNAL-GROUPS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SIGNAL-GROUP" type="{http://www.asam.net/xml/fbx}SIGNAL-GROUP-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PDU-REQS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PDU-REQ" type="{http://www.asam.net/xml/fbx}PDU-REQ-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQUIREMENTS", propOrder = {
    "portreqs",
    "functionreqs",
    "signalgroups",
    "pdureqs"
})
public class REQUIREMENTS {

    @XmlElement(name = "PORT-REQS")
    protected REQUIREMENTS.PORTREQS portreqs;
    @XmlElement(name = "FUNCTION-REQS")
    protected REQUIREMENTS.FUNCTIONREQS functionreqs;
    @XmlElement(name = "SIGNAL-GROUPS")
    protected REQUIREMENTS.SIGNALGROUPS signalgroups;
    @XmlElement(name = "PDU-REQS")
    protected REQUIREMENTS.PDUREQS pdureqs;

    /**
     * Gets the value of the portreqs property.
     * 
     * @return
     *     possible object is
     *     {@link REQUIREMENTS.PORTREQS }
     *     
     */
    public REQUIREMENTS.PORTREQS getPORTREQS() {
        return portreqs;
    }

    /**
     * Sets the value of the portreqs property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUIREMENTS.PORTREQS }
     *     
     */
    public void setPORTREQS(REQUIREMENTS.PORTREQS value) {
        this.portreqs = value;
    }

    /**
     * Gets the value of the functionreqs property.
     * 
     * @return
     *     possible object is
     *     {@link REQUIREMENTS.FUNCTIONREQS }
     *     
     */
    public REQUIREMENTS.FUNCTIONREQS getFUNCTIONREQS() {
        return functionreqs;
    }

    /**
     * Sets the value of the functionreqs property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUIREMENTS.FUNCTIONREQS }
     *     
     */
    public void setFUNCTIONREQS(REQUIREMENTS.FUNCTIONREQS value) {
        this.functionreqs = value;
    }

    /**
     * Gets the value of the signalgroups property.
     * 
     * @return
     *     possible object is
     *     {@link REQUIREMENTS.SIGNALGROUPS }
     *     
     */
    public REQUIREMENTS.SIGNALGROUPS getSIGNALGROUPS() {
        return signalgroups;
    }

    /**
     * Sets the value of the signalgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUIREMENTS.SIGNALGROUPS }
     *     
     */
    public void setSIGNALGROUPS(REQUIREMENTS.SIGNALGROUPS value) {
        this.signalgroups = value;
    }

    /**
     * Gets the value of the pdureqs property.
     * 
     * @return
     *     possible object is
     *     {@link REQUIREMENTS.PDUREQS }
     *     
     */
    public REQUIREMENTS.PDUREQS getPDUREQS() {
        return pdureqs;
    }

    /**
     * Sets the value of the pdureqs property.
     * 
     * @param value
     *     allowed object is
     *     {@link REQUIREMENTS.PDUREQS }
     *     
     */
    public void setPDUREQS(REQUIREMENTS.PDUREQS value) {
        this.pdureqs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FUNCTION-REQ" type="{http://www.asam.net/xml/fbx}FUNCTION-REQ-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "functionreq"
    })
    public static class FUNCTIONREQS {

        @XmlElement(name = "FUNCTION-REQ", required = true)
        protected List<FUNCTIONREQTYPE> functionreq;

        /**
         * Gets the value of the functionreq property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the functionreq property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFUNCTIONREQ().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FUNCTIONREQTYPE }
         * 
         * 
         */
        public List<FUNCTIONREQTYPE> getFUNCTIONREQ() {
            if (functionreq == null) {
                functionreq = new ArrayList<FUNCTIONREQTYPE>();
            }
            return this.functionreq;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PDU-REQ" type="{http://www.asam.net/xml/fbx}PDU-REQ-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pdureq"
    })
    public static class PDUREQS {

        @XmlElement(name = "PDU-REQ", required = true)
        protected List<PDUREQTYPE> pdureq;

        /**
         * Gets the value of the pdureq property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pdureq property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPDUREQ().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PDUREQTYPE }
         * 
         * 
         */
        public List<PDUREQTYPE> getPDUREQ() {
            if (pdureq == null) {
                pdureq = new ArrayList<PDUREQTYPE>();
            }
            return this.pdureq;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PORT-REQ" type="{http://www.asam.net/xml/fbx}PORT-REQ-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "portreq"
    })
    public static class PORTREQS {

        @XmlElement(name = "PORT-REQ", required = true)
        protected List<PORTREQTYPE> portreq;

        /**
         * Gets the value of the portreq property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the portreq property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPORTREQ().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PORTREQTYPE }
         * 
         * 
         */
        public List<PORTREQTYPE> getPORTREQ() {
            if (portreq == null) {
                portreq = new ArrayList<PORTREQTYPE>();
            }
            return this.portreq;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SIGNAL-GROUP" type="{http://www.asam.net/xml/fbx}SIGNAL-GROUP-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signalgroup"
    })
    public static class SIGNALGROUPS {

        @XmlElement(name = "SIGNAL-GROUP", required = true)
        protected List<SIGNALGROUPTYPE> signalgroup;

        /**
         * Gets the value of the signalgroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the signalgroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSIGNALGROUP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SIGNALGROUPTYPE }
         * 
         * 
         */
        public List<SIGNALGROUPTYPE> getSIGNALGROUP() {
            if (signalgroup == null) {
                signalgroup = new ArrayList<SIGNALGROUPTYPE>();
            }
            return this.signalgroup;
        }

    }

}
