//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Base content model for all ELEMENTS
 * 
 * <p>Java class for REVISED-ELEMENT-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REVISED-ELEMENT-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}NAMED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="ELEMENT-REVISIONS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ELEMENT-REVISION" type="{http://www.asam.net/xml}REVISION-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PRODUCT-REF" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REVISED-ELEMENT-TYPE", propOrder = {
    "elementrevisions",
    "productref"
})
@XmlSeeAlso({
    PDUTYPE.class,
    CLUSTERTYPE.class,
    COMPOSITETYPE.class,
    SIGNALGROUPTYPE.class,
    TPCONFIGTYPE.class,
    CHANNELTYPE.class,
    ECUTYPE.class,
    SIGNALTYPE.class,
    GATEWAYTYPE.class,
    CODINGTYPE.class,
    NMCONFIGTYPE.class,
    FUNCTIONTYPE.class,
    FRAMETYPE.class
})
public abstract class REVISEDELEMENTTYPE
    extends NAMEDELEMENTTYPE
{

    @XmlElement(name = "ELEMENT-REVISIONS")
    protected REVISEDELEMENTTYPE.ELEMENTREVISIONS elementrevisions;
    @XmlElement(name = "PRODUCT-REF")
    protected REVISEDELEMENTTYPE.PRODUCTREF productref;

    /**
     * Gets the value of the elementrevisions property.
     * 
     * @return
     *     possible object is
     *     {@link REVISEDELEMENTTYPE.ELEMENTREVISIONS }
     *     
     */
    public REVISEDELEMENTTYPE.ELEMENTREVISIONS getELEMENTREVISIONS() {
        return elementrevisions;
    }

    /**
     * Sets the value of the elementrevisions property.
     * 
     * @param value
     *     allowed object is
     *     {@link REVISEDELEMENTTYPE.ELEMENTREVISIONS }
     *     
     */
    public void setELEMENTREVISIONS(REVISEDELEMENTTYPE.ELEMENTREVISIONS value) {
        this.elementrevisions = value;
    }

    /**
     * Gets the value of the productref property.
     * 
     * @return
     *     possible object is
     *     {@link REVISEDELEMENTTYPE.PRODUCTREF }
     *     
     */
    public REVISEDELEMENTTYPE.PRODUCTREF getPRODUCTREF() {
        return productref;
    }

    /**
     * Sets the value of the productref property.
     * 
     * @param value
     *     allowed object is
     *     {@link REVISEDELEMENTTYPE.PRODUCTREF }
     *     
     */
    public void setPRODUCTREF(REVISEDELEMENTTYPE.PRODUCTREF value) {
        this.productref = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ELEMENT-REVISION" type="{http://www.asam.net/xml}REVISION-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elementrevision"
    })
    public static class ELEMENTREVISIONS {

        @XmlElement(name = "ELEMENT-REVISION", required = true)
        protected List<REVISIONTYPE> elementrevision;

        /**
         * Gets the value of the elementrevision property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the elementrevision property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getELEMENTREVISION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link REVISIONTYPE }
         * 
         * 
         */
        public List<REVISIONTYPE> getELEMENTREVISION() {
            if (elementrevision == null) {
                elementrevision = new ArrayList<REVISIONTYPE>();
            }
            return this.elementrevision;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PRODUCTREF {

        @XmlAttribute(name = "ID-REF", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object idref;

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIDREF() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIDREF(Object value) {
            this.idref = value;
        }

    }

}
