//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * For reusability scale constraints content model is specified using a type definition.
 * 
 * <p>Java class for SCALE-CONSTR-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SCALE-CONSTR-TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SCALE-CONSTR" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.asam.net/xml}LOWER-LIMIT" minOccurs="0"/>
 *                   &lt;element ref="{http://www.asam.net/xml}UPPER-LIMIT" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="VALIDITY" type="{http://www.asam.net/xml}VALIDITY" default="VALID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SCALE-CONSTR-TYPE", namespace = "http://www.asam.net/xml", propOrder = {
    "scaleconstr"
})
public class SCALECONSTRTYPE {

    @XmlElement(name = "SCALE-CONSTR", required = true)
    protected List<SCALECONSTRTYPE.SCALECONSTR> scaleconstr;

    /**
     * Gets the value of the scaleconstr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scaleconstr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSCALECONSTR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SCALECONSTRTYPE.SCALECONSTR }
     * 
     * 
     */
    public List<SCALECONSTRTYPE.SCALECONSTR> getSCALECONSTR() {
        if (scaleconstr == null) {
            scaleconstr = new ArrayList<SCALECONSTRTYPE.SCALECONSTR>();
        }
        return this.scaleconstr;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.asam.net/xml}LOWER-LIMIT" minOccurs="0"/>
     *         &lt;element ref="{http://www.asam.net/xml}UPPER-LIMIT" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="VALIDITY" type="{http://www.asam.net/xml}VALIDITY" default="VALID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lowerlimit",
        "upperlimit"
    })
    public static class SCALECONSTR {

        @XmlElement(name = "LOWER-LIMIT", namespace = "http://www.asam.net/xml")
        protected INTERVALTYPE lowerlimit;
        @XmlElement(name = "UPPER-LIMIT", namespace = "http://www.asam.net/xml")
        protected INTERVALTYPE upperlimit;
        @XmlAttribute(name = "VALIDITY")
        protected VALIDITY validity;

        /**
         * Gets the value of the lowerlimit property.
         * 
         * @return
         *     possible object is
         *     {@link INTERVALTYPE }
         *     
         */
        public INTERVALTYPE getLOWERLIMIT() {
            return lowerlimit;
        }

        /**
         * Sets the value of the lowerlimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link INTERVALTYPE }
         *     
         */
        public void setLOWERLIMIT(INTERVALTYPE value) {
            this.lowerlimit = value;
        }

        /**
         * Gets the value of the upperlimit property.
         * 
         * @return
         *     possible object is
         *     {@link INTERVALTYPE }
         *     
         */
        public INTERVALTYPE getUPPERLIMIT() {
            return upperlimit;
        }

        /**
         * Sets the value of the upperlimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link INTERVALTYPE }
         *     
         */
        public void setUPPERLIMIT(INTERVALTYPE value) {
            this.upperlimit = value;
        }

        /**
         * Gets the value of the validity property.
         * 
         * @return
         *     possible object is
         *     {@link VALIDITY }
         *     
         */
        public VALIDITY getVALIDITY() {
            if (validity == null) {
                return VALIDITY.VALID;
            } else {
                return validity;
            }
        }

        /**
         * Sets the value of the validity property.
         * 
         * @param value
         *     allowed object is
         *     {@link VALIDITY }
         *     
         */
        public void setVALIDITY(VALIDITY value) {
            this.validity = value;
        }

    }

}
