//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Fragment positions of the enclosing multiplexer part (PDU)
 * 
 * <p>Java class for SEGMENT-POSITIONS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SEGMENT-POSITIONS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SEGMENT-POSITION">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{http://www.asam.net/xml/fbx}COMMON-LAYOUT-DETAILS"/>
 *                   &lt;element ref="{http://www.asam.net/xml}BIT-LENGTH"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SEGMENT-POSITIONS", propOrder = {
    "segmentposition"
})
public class SEGMENTPOSITIONS {

    @XmlElement(name = "SEGMENT-POSITION", required = true)
    protected SEGMENTPOSITIONS.SEGMENTPOSITION segmentposition;

    /**
     * Gets the value of the segmentposition property.
     * 
     * @return
     *     possible object is
     *     {@link SEGMENTPOSITIONS.SEGMENTPOSITION }
     *     
     */
    public SEGMENTPOSITIONS.SEGMENTPOSITION getSEGMENTPOSITION() {
        return segmentposition;
    }

    /**
     * Sets the value of the segmentposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEGMENTPOSITIONS.SEGMENTPOSITION }
     *     
     */
    public void setSEGMENTPOSITION(SEGMENTPOSITIONS.SEGMENTPOSITION value) {
        this.segmentposition = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://www.asam.net/xml/fbx}COMMON-LAYOUT-DETAILS"/>
     *         &lt;element ref="{http://www.asam.net/xml}BIT-LENGTH"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bitposition",
        "ishighlowbyteorder",
        "sequencenumber",
        "bitlength"
    })
    public static class SEGMENTPOSITION {

        @XmlElement(name = "BIT-POSITION")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer bitposition;
        @XmlElement(name = "IS-HIGH-LOW-BYTE-ORDER")
        protected Boolean ishighlowbyteorder;
        @XmlElement(name = "SEQUENCE-NUMBER")
        @XmlSchemaType(name = "unsignedShort")
        protected Integer sequencenumber;
        @XmlElement(name = "BIT-LENGTH", namespace = "http://www.asam.net/xml")
        @XmlSchemaType(name = "unsignedInt")
        protected long bitlength;

        /**
         * Gets the value of the bitposition property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getBITPOSITION() {
            return bitposition;
        }

        /**
         * Sets the value of the bitposition property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBITPOSITION(Integer value) {
            this.bitposition = value;
        }

        /**
         * Gets the value of the ishighlowbyteorder property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isISHIGHLOWBYTEORDER() {
            return ishighlowbyteorder;
        }

        /**
         * Sets the value of the ishighlowbyteorder property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setISHIGHLOWBYTEORDER(Boolean value) {
            this.ishighlowbyteorder = value;
        }

        /**
         * Gets the value of the sequencenumber property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSEQUENCENUMBER() {
            return sequencenumber;
        }

        /**
         * Sets the value of the sequencenumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSEQUENCENUMBER(Integer value) {
            this.sequencenumber = value;
        }

        /**
         * Gets the value of the bitlength property.
         * 
         */
        public long getBITLENGTH() {
            return bitlength;
        }

        /**
         * Sets the value of the bitlength property.
         * 
         */
        public void setBITLENGTH(long value) {
            this.bitlength = value;
        }

    }

}
