//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Content model for the entity SIGNAL. 
 * 
 * <p>Java class for SIGNAL-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SIGNAL-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="DEFAULT-VALUE" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CODING-REF">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SIGNAL-TYPE" type="{http://www.asam.net/xml/fbx}SIGNAL-TYPE-TYPE" minOccurs="0"/>
 *         &lt;element name="PRIORITY" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="ECU-SENDING-BEHAVIORS" type="{http://www.asam.net/xml/fbx}ECU-SENDING-BEHAVIORS" minOccurs="0"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-SIGNAL-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SIGNAL-TYPE", propOrder = {
    "defaultvalue",
    "codingref",
    "signaltype",
    "priority",
    "ecusendingbehaviors",
    "manufacturerextension"
})
public class SIGNALTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "DEFAULT-VALUE")
    protected SIGNALTYPE.DEFAULTVALUE defaultvalue;
    @XmlElement(name = "CODING-REF", required = true)
    protected SIGNALTYPE.CODINGREF codingref;
    @XmlElement(name = "SIGNAL-TYPE")
    protected SIGNALTYPETYPE signaltype;
    @XmlElement(name = "PRIORITY")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger priority;
    @XmlElement(name = "ECU-SENDING-BEHAVIORS")
    protected ECUSENDINGBEHAVIORS ecusendingbehaviors;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERSIGNALEXTENSION manufacturerextension;

    /**
     * Gets the value of the defaultvalue property.
     * 
     * @return
     *     possible object is
     *     {@link SIGNALTYPE.DEFAULTVALUE }
     *     
     */
    public SIGNALTYPE.DEFAULTVALUE getDEFAULTVALUE() {
        return defaultvalue;
    }

    /**
     * Sets the value of the defaultvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGNALTYPE.DEFAULTVALUE }
     *     
     */
    public void setDEFAULTVALUE(SIGNALTYPE.DEFAULTVALUE value) {
        this.defaultvalue = value;
    }

    /**
     * Gets the value of the codingref property.
     * 
     * @return
     *     possible object is
     *     {@link SIGNALTYPE.CODINGREF }
     *     
     */
    public SIGNALTYPE.CODINGREF getCODINGREF() {
        return codingref;
    }

    /**
     * Sets the value of the codingref property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGNALTYPE.CODINGREF }
     *     
     */
    public void setCODINGREF(SIGNALTYPE.CODINGREF value) {
        this.codingref = value;
    }

    /**
     * Gets the value of the signaltype property.
     * 
     * @return
     *     possible object is
     *     {@link SIGNALTYPETYPE }
     *     
     */
    public SIGNALTYPETYPE getSIGNALTYPE() {
        return signaltype;
    }

    /**
     * Sets the value of the signaltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIGNALTYPETYPE }
     *     
     */
    public void setSIGNALTYPE(SIGNALTYPETYPE value) {
        this.signaltype = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPRIORITY() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPRIORITY(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the ecusendingbehaviors property.
     * 
     * @return
     *     possible object is
     *     {@link ECUSENDINGBEHAVIORS }
     *     
     */
    public ECUSENDINGBEHAVIORS getECUSENDINGBEHAVIORS() {
        return ecusendingbehaviors;
    }

    /**
     * Sets the value of the ecusendingbehaviors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECUSENDINGBEHAVIORS }
     *     
     */
    public void setECUSENDINGBEHAVIORS(ECUSENDINGBEHAVIORS value) {
        this.ecusendingbehaviors = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERSIGNALEXTENSION }
     *     
     */
    public MANUFACTURERSIGNALEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERSIGNALEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERSIGNALEXTENSION value) {
        this.manufacturerextension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ID-REF" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CODINGREF {

        @XmlAttribute(name = "ID-REF", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object idref;

        /**
         * Gets the value of the idref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIDREF() {
            return idref;
        }

        /**
         * Sets the value of the idref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIDREF(Object value) {
            this.idref = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DEFAULTVALUE {

        @XmlValue
        protected double value;

        /**
         * Gets the value of the value property.
         * 
         */
        public double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(double value) {
            this.value = value;
        }

    }

}
