//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Signal state that must rule that the referencing timing is executed. To enable the description of combined tirggers the occurence of SIGNAL-TRIGGER as well as of SIGNAL-STATE combined with SIGNAL-INSTANCE-REF is unbounded. Use one trigger with many states, if these states must rule simultaneously (AND related) for execution. Use a separate trigger for each state if only one state needs to rule for execution.
 * 
 * <p>Java class for SIGNAL-TRIGGER complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SIGNAL-TRIGGER">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="SIGNAL-STATE" type="{http://www.asam.net/xml/fbx}EXECUTE-CONDITION-SIGNAL-STATE-TYPE"/>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}SIGNAL-INSTANCE-REF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SIGNAL-TRIGGER", propOrder = {
    "signalstateAndSIGNALINSTANCEREF"
})
public class SIGNALTRIGGER {

    @XmlElements({
        @XmlElement(name = "SIGNAL-INSTANCE-REF", required = true, type = SIGNALINSTANCEREF.class),
        @XmlElement(name = "SIGNAL-STATE", required = true, type = EXECUTECONDITIONSIGNALSTATETYPE.class)
    })
    protected List<Object> signalstateAndSIGNALINSTANCEREF;

    /**
     * Gets the value of the signalstateAndSIGNALINSTANCEREF property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signalstateAndSIGNALINSTANCEREF property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSIGNALSTATEAndSIGNALINSTANCEREF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SIGNALINSTANCEREF }
     * {@link EXECUTECONDITIONSIGNALSTATETYPE }
     * 
     * 
     */
    public List<Object> getSIGNALSTATEAndSIGNALINSTANCEREF() {
        if (signalstateAndSIGNALINSTANCEREF == null) {
            signalstateAndSIGNALINSTANCEREF = new ArrayList<Object>();
        }
        return this.signalstateAndSIGNALINSTANCEREF;
    }

}
