//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Content model for the entity SIGNAL-GROUP
 * 
 * <p>Java class for SIGNAL-GROUP-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SIGNAL-GROUP-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml}BIT-LENGTH" minOccurs="0"/>
 *         &lt;element ref="{http://www.asam.net/xml/fbx}IDENTIFIER" minOccurs="0"/>
 *         &lt;element name="ORDERED-SIGNALS" type="{http://www.asam.net/xml/fbx}ORDERED-SIGNALS" minOccurs="0"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-SIGNAL-GROUP-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SIGNAL-GROUP-TYPE", propOrder = {
    "bitlength",
    "identifier",
    "orderedsignals",
    "manufacturerextension"
})
public class SIGNALGROUPTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "BIT-LENGTH", namespace = "http://www.asam.net/xml")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bitlength;
    @XmlElement(name = "IDENTIFIER")
    protected IDENTIFIER identifier;
    @XmlElement(name = "ORDERED-SIGNALS")
    protected ORDEREDSIGNALS orderedsignals;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERSIGNALGROUPEXTENSION manufacturerextension;

    /**
     * Gets the value of the bitlength property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBITLENGTH() {
        return bitlength;
    }

    /**
     * Sets the value of the bitlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBITLENGTH(Long value) {
        this.bitlength = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IDENTIFIER }
     *     
     */
    public IDENTIFIER getIDENTIFIER() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDENTIFIER }
     *     
     */
    public void setIDENTIFIER(IDENTIFIER value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the orderedsignals property.
     * 
     * @return
     *     possible object is
     *     {@link ORDEREDSIGNALS }
     *     
     */
    public ORDEREDSIGNALS getORDEREDSIGNALS() {
        return orderedsignals;
    }

    /**
     * Sets the value of the orderedsignals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDEREDSIGNALS }
     *     
     */
    public void setORDEREDSIGNALS(ORDEREDSIGNALS value) {
        this.orderedsignals = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERSIGNALGROUPEXTENSION }
     *     
     */
    public MANUFACTURERSIGNALGROUPEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERSIGNALGROUPEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERSIGNALGROUPEXTENSION value) {
        this.manufacturerextension = value;
    }

}
