//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Static part of the multiplexer. This part is independent of the switch value
 * 
 * <p>Java class for STATIC-PART complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="STATIC-PART">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}MUX-PART-TYPE">
 *       &lt;sequence>
 *         &lt;element name="STATIC-PDU-INSTANCE" type="{http://www.asam.net/xml/fbx}GENERIC-PDU-INSTANCE-TYPE"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "STATIC-PART", propOrder = {
    "staticpduinstance"
})
public class STATICPART
    extends MUXPARTTYPE
{

    @XmlElement(name = "STATIC-PDU-INSTANCE", required = true)
    protected GENERICPDUINSTANCETYPE staticpduinstance;

    /**
     * Gets the value of the staticpduinstance property.
     * 
     * @return
     *     possible object is
     *     {@link GENERICPDUINSTANCETYPE }
     *     
     */
    public GENERICPDUINSTANCETYPE getSTATICPDUINSTANCE() {
        return staticpduinstance;
    }

    /**
     * Sets the value of the staticpduinstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link GENERICPDUINSTANCETYPE }
     *     
     */
    public void setSTATICPDUINSTANCE(GENERICPDUINSTANCETYPE value) {
        this.staticpduinstance = value;
    }

}
