//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Reserved space in a PDU, used to encode what variation of signals is currently transported at the position given by the corresponding dynamic part
 * 
 * <p>Java class for SWITCH complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SWITCH">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}NAMED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.asam.net/xml/fbx}COMMON-LAYOUT-DETAILS"/>
 *         &lt;element ref="{http://www.asam.net/xml}BIT-LENGTH"/>
 *         &lt;element name="MANUFACTURER-EXTENSION" type="{http://www.asam.net/xml/fbx}MANUFACTURER-SWITCH-EXTENSION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SWITCH", propOrder = {
    "bitposition",
    "ishighlowbyteorder",
    "sequencenumber",
    "bitlength",
    "manufacturerextension"
})
public class SWITCH
    extends NAMEDELEMENTTYPE
{

    @XmlElement(name = "BIT-POSITION")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer bitposition;
    @XmlElement(name = "IS-HIGH-LOW-BYTE-ORDER")
    protected Boolean ishighlowbyteorder;
    @XmlElement(name = "SEQUENCE-NUMBER")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer sequencenumber;
    @XmlElement(name = "BIT-LENGTH", namespace = "http://www.asam.net/xml")
    @XmlSchemaType(name = "unsignedInt")
    protected long bitlength;
    @XmlElement(name = "MANUFACTURER-EXTENSION")
    protected MANUFACTURERSWITCHEXTENSION manufacturerextension;

    /**
     * Gets the value of the bitposition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBITPOSITION() {
        return bitposition;
    }

    /**
     * Sets the value of the bitposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBITPOSITION(Integer value) {
        this.bitposition = value;
    }

    /**
     * Gets the value of the ishighlowbyteorder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISHIGHLOWBYTEORDER() {
        return ishighlowbyteorder;
    }

    /**
     * Sets the value of the ishighlowbyteorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISHIGHLOWBYTEORDER(Boolean value) {
        this.ishighlowbyteorder = value;
    }

    /**
     * Gets the value of the sequencenumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSEQUENCENUMBER() {
        return sequencenumber;
    }

    /**
     * Sets the value of the sequencenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSEQUENCENUMBER(Integer value) {
        this.sequencenumber = value;
    }

    /**
     * Gets the value of the bitlength property.
     * 
     */
    public long getBITLENGTH() {
        return bitlength;
    }

    /**
     * Sets the value of the bitlength property.
     * 
     */
    public void setBITLENGTH(long value) {
        this.bitlength = value;
    }

    /**
     * Gets the value of the manufacturerextension property.
     * 
     * @return
     *     possible object is
     *     {@link MANUFACTURERSWITCHEXTENSION }
     *     
     */
    public MANUFACTURERSWITCHEXTENSION getMANUFACTUREREXTENSION() {
        return manufacturerextension;
    }

    /**
     * Sets the value of the manufacturerextension property.
     * 
     * @param value
     *     allowed object is
     *     {@link MANUFACTURERSWITCHEXTENSION }
     *     
     */
    public void setMANUFACTUREREXTENSION(MANUFACTURERSWITCHEXTENSION value) {
        this.manufacturerextension = value;
    }

}
