//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TERMINATION.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TERMINATION">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="NONE"/>
 *     &lt;enumeration value="ZERO"/>
 *     &lt;enumeration value="HEX-FF"/>
 *     &lt;enumeration value="LENGTH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TERMINATION", namespace = "http://www.asam.net/xml")
@XmlEnum
public enum TERMINATION {

    NONE("NONE"),
    ZERO("ZERO"),
    @XmlEnumValue("HEX-FF")
    HEX_FF("HEX-FF"),
    LENGTH("LENGTH");
    private final String value;

    TERMINATION(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TERMINATION fromValue(String v) {
        for (TERMINATION c: TERMINATION.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
