//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Extension point for the transport layer schemata.
 * 
 * <p>Java class for TP-CONFIG-TYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TP-CONFIG-TYPE">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.asam.net/xml/fbx}REVISED-ELEMENT-TYPE">
 *       &lt;sequence>
 *         &lt;element name="TP-ADDRESSES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TP-ADDRESS" type="{http://www.asam.net/xml/fbx}TP-ADDRESS-TYPE" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TP-CONFIG-TYPE", propOrder = {
    "tpaddresses"
})
public class TPCONFIGTYPE
    extends REVISEDELEMENTTYPE
{

    @XmlElement(name = "TP-ADDRESSES", required = true)
    protected TPCONFIGTYPE.TPADDRESSES tpaddresses;

    /**
     * Gets the value of the tpaddresses property.
     * 
     * @return
     *     possible object is
     *     {@link TPCONFIGTYPE.TPADDRESSES }
     *     
     */
    public TPCONFIGTYPE.TPADDRESSES getTPADDRESSES() {
        return tpaddresses;
    }

    /**
     * Sets the value of the tpaddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPCONFIGTYPE.TPADDRESSES }
     *     
     */
    public void setTPADDRESSES(TPCONFIGTYPE.TPADDRESSES value) {
        this.tpaddresses = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TP-ADDRESS" type="{http://www.asam.net/xml/fbx}TP-ADDRESS-TYPE" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tpaddress"
    })
    public static class TPADDRESSES {

        @XmlElement(name = "TP-ADDRESS", required = true)
        protected List<TPADDRESSTYPE> tpaddress;

        /**
         * Gets the value of the tpaddress property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tpaddress property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTPADDRESS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TPADDRESSTYPE }
         * 
         * 
         */
        public List<TPADDRESSTYPE> getTPADDRESS() {
            if (tpaddress == null) {
                tpaddress = new ArrayList<TPADDRESSTYPE>();
            }
            return this.tpaddress;
        }

    }

}
