//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 02:41:15 PM MESZ 
//


package systemModel.fibexImporter.xsd31;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.asam.net/xml}ADMIN-DATA" minOccurs="0"/>
 *         &lt;element name="PHYSICAL-DIMENSIONS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PHYSICAL-DIMENSION" type="{http://www.asam.net/xml}PHYSICAL-DIMENSION" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UNITGROUPS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UNITGROUP" type="{http://www.asam.net/xml}UNITGROUP" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UNITS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="UNIT" type="{http://www.asam.net/xml}UNIT" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "admindata",
    "physicaldimensions",
    "unitgroups",
    "units"
})
@XmlRootElement(name = "UNIT-SPEC", namespace = "http://www.asam.net/xml")
public class UNITSPEC {

    @XmlElement(name = "ADMIN-DATA", namespace = "http://www.asam.net/xml")
    protected ADMINDATA admindata;
    @XmlElement(name = "PHYSICAL-DIMENSIONS", namespace = "http://www.asam.net/xml")
    protected UNITSPEC.PHYSICALDIMENSIONS physicaldimensions;
    @XmlElement(name = "UNITGROUPS", namespace = "http://www.asam.net/xml")
    protected UNITSPEC.UNITGROUPS unitgroups;
    @XmlElement(name = "UNITS", namespace = "http://www.asam.net/xml")
    protected UNITSPEC.UNITS units;

    /**
     * Gets the value of the admindata property.
     * 
     * @return
     *     possible object is
     *     {@link ADMINDATA }
     *     
     */
    public ADMINDATA getADMINDATA() {
        return admindata;
    }

    /**
     * Sets the value of the admindata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADMINDATA }
     *     
     */
    public void setADMINDATA(ADMINDATA value) {
        this.admindata = value;
    }

    /**
     * Gets the value of the physicaldimensions property.
     * 
     * @return
     *     possible object is
     *     {@link UNITSPEC.PHYSICALDIMENSIONS }
     *     
     */
    public UNITSPEC.PHYSICALDIMENSIONS getPHYSICALDIMENSIONS() {
        return physicaldimensions;
    }

    /**
     * Sets the value of the physicaldimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNITSPEC.PHYSICALDIMENSIONS }
     *     
     */
    public void setPHYSICALDIMENSIONS(UNITSPEC.PHYSICALDIMENSIONS value) {
        this.physicaldimensions = value;
    }

    /**
     * Gets the value of the unitgroups property.
     * 
     * @return
     *     possible object is
     *     {@link UNITSPEC.UNITGROUPS }
     *     
     */
    public UNITSPEC.UNITGROUPS getUNITGROUPS() {
        return unitgroups;
    }

    /**
     * Sets the value of the unitgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNITSPEC.UNITGROUPS }
     *     
     */
    public void setUNITGROUPS(UNITSPEC.UNITGROUPS value) {
        this.unitgroups = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link UNITSPEC.UNITS }
     *     
     */
    public UNITSPEC.UNITS getUNITS() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNITSPEC.UNITS }
     *     
     */
    public void setUNITS(UNITSPEC.UNITS value) {
        this.units = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PHYSICAL-DIMENSION" type="{http://www.asam.net/xml}PHYSICAL-DIMENSION" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "physicaldimension"
    })
    public static class PHYSICALDIMENSIONS {

        @XmlElement(name = "PHYSICAL-DIMENSION", namespace = "http://www.asam.net/xml", required = true)
        protected List<PHYSICALDIMENSION> physicaldimension;

        /**
         * Gets the value of the physicaldimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the physicaldimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPHYSICALDIMENSION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PHYSICALDIMENSION }
         * 
         * 
         */
        public List<PHYSICALDIMENSION> getPHYSICALDIMENSION() {
            if (physicaldimension == null) {
                physicaldimension = new ArrayList<PHYSICALDIMENSION>();
            }
            return this.physicaldimension;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UNITGROUP" type="{http://www.asam.net/xml}UNITGROUP" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unitgroup"
    })
    public static class UNITGROUPS {

        @XmlElement(name = "UNITGROUP", namespace = "http://www.asam.net/xml", required = true)
        protected List<UNITGROUP> unitgroup;

        /**
         * Gets the value of the unitgroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unitgroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUNITGROUP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UNITGROUP }
         * 
         * 
         */
        public List<UNITGROUP> getUNITGROUP() {
            if (unitgroup == null) {
                unitgroup = new ArrayList<UNITGROUP>();
            }
            return this.unitgroup;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="UNIT" type="{http://www.asam.net/xml}UNIT" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unit"
    })
    public static class UNITS {

        @XmlElement(name = "UNIT", namespace = "http://www.asam.net/xml", required = true)
        protected List<UNIT> unit;

        /**
         * Gets the value of the unit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUNIT().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UNIT }
         * 
         * 
         */
        public List<UNIT> getUNIT() {
            if (unit == null) {
                unit = new ArrayList<UNIT>();
            }
            return this.unit;
        }

    }

}
